In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/Combined/imputed_combined.csv")

In [3]:
cols = ['Rndrng_Prvdr_Crdntls',
'Rndrng_Prvdr_Gndr', 
'Rndrng_Prvdr_Type',
'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 
'Tot_HCPCS_Cds', 
'Tot_Benes_x',
'Tot_Srvcs', 
'Tot_Sbmtd_Chrg', 
'Tot_Mdcr_Alowd_Amt',
'Tot_Mdcr_Pymt_Amt', 
'Tot_Mdcr_Stdzd_Amt', 
'Drug_Sprsn_Ind_x',
'Drug_Tot_HCPCS_Cds', 
'Drug_Tot_Benes', 
'Drug_Tot_Srvcs',
'Drug_Sbmtd_Chrg', 
'Drug_Mdcr_Alowd_Amt', 
'Drug_Mdcr_Pymt_Amt',
       'Drug_Mdcr_Stdzd_Amt', 'Med_Sprsn_Ind', 'Med_Tot_HCPCS_Cds',
       'Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
       'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',
       'Bene_Avg_Age_x', 'Bene_Age_LT_65_Cnt_x', 'Bene_Age_65_74_Cnt_x',
       'Bene_Age_75_84_Cnt_x', 'Bene_Age_GT_84_Cnt_x', 'Bene_Feml_Cnt_x',
       'Bene_Male_Cnt_x', 'Bene_Race_Wht_Cnt_x', 'Bene_Race_Black_Cnt_x',
       'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt_x',
       'Bene_Race_NatInd_Cnt', 'Bene_Race_Othr_Cnt_x', 'Bene_Dual_Cnt_x',
       'Bene_Ndual_Cnt_x', 'Bene_CC_AF_Pct_x', 'Bene_CC_Alzhmr_Pct_x',
       'Bene_CC_Asthma_Pct_x', 'Bene_CC_Cncr_Pct_x', 'Bene_CC_CHF_Pct_x',
       'Bene_CC_CKD_Pct_x', 'Bene_CC_COPD_Pct_x', 'Bene_CC_Dprssn_Pct_x',
       'Bene_CC_Dbts_Pct_x', 'Bene_CC_Hyplpdma_Pct_x',
       'Bene_CC_Hyprtnsn_Pct_x', 'Bene_CC_IHD_Pct_x', 'Bene_CC_Opo_Pct_x',
       'Bene_CC_RAOA_Pct_x', 'Bene_CC_Sz_Pct_x', 'Bene_CC_Strok_Pct_x',
       'Bene_Avg_Risk_Scre_x', 'Rndrng_NPI', 'Fraud_x', 'FraudType_x',
'Prscrbr_Crdntls',
       'Prscrbr_Type_src', 'Tot_Clms', 'Tot_30day_Fills',
       'Tot_Drug_Cst', 'Tot_Day_Suply', 'GE65_Sprsn_Flag',
       'GE65_Tot_Clms', 'GE65_Tot_30day_Fills', 'GE65_Tot_Drug_Cst',
       'GE65_Tot_Day_Suply', 'GE65_Bene_Sprsn_Flag', 'GE65_Tot_Benes',
       'Brnd_Sprsn_Flag', 'Brnd_Tot_Clms', 'Brnd_Tot_Drug_Cst',
       'Gnrc_Sprsn_Flag', 'Gnrc_Tot_Clms', 'Gnrc_Tot_Drug_Cst',
       'Othr_Sprsn_Flag', 'Othr_Tot_Clms', 'Othr_Tot_Drug_Cst',
       'MAPD_Sprsn_Flag', 'MAPD_Tot_Clms', 'MAPD_Tot_Drug_Cst',
       'PDP_Sprsn_Flag', 'PDP_Tot_Clms', 'PDP_Tot_Drug_Cst',
       'LIS_Sprsn_Flag', 'LIS_Tot_Clms', 'LIS_Drug_Cst',
       'NonLIS_Sprsn_Flag', 'NonLIS_Tot_Clms', 'NonLIS_Drug_Cst',
       'Opioid_Tot_Clms', 'Opioid_Tot_Drug_Cst', 'Opioid_Tot_Suply',
       'Opioid_Tot_Benes', 'Opioid_Prscrbr_Rate', 'Opioid_LA_Tot_Clms',
       'Opioid_LA_Tot_Drug_Cst', 'Opioid_LA_Tot_Suply',
       'Opioid_LA_Tot_Benes', 'Opioid_LA_Prscrbr_Rate', 'Antbtc_Tot_Clms',
       'Antbtc_Tot_Drug_Cst', 'Antbtc_Tot_Benes',
       'Antpsyct_GE65_Sprsn_Flag', 'Antpsyct_GE65_Tot_Clms',
       'Antpsyct_GE65_Tot_Drug_Cst', 'Antpsyct_GE65_Tot_Benes',
       'Bene_Race_Api_Cnt_x', 
       'Bene_Race_Natind_Cnt_x', 
       'Rfrg_Prvdr_Type_Flag', 'Tot_Suplrs', 'Tot_Suplr_HCPCS_Cds',
       'Tot_Suplr_Benes', 'Tot_Suplr_Clms', 'Tot_Suplr_Srvcs',
       'Suplr_Sbmtd_Chrgs', 'Suplr_Mdcr_Alowd_Amt', 'Suplr_Mdcr_Pymt_Amt',
       'Suplr_Mdcr_Stdzd_Pymt_Amt', 'DME_Sprsn_Ind', 'DME_Tot_Suplrs',
       'DME_Tot_Suplr_HCPCS_Cds', 'DME_Tot_Suplr_Benes',
       'DME_Tot_Suplr_Clms', 'DME_Tot_Suplr_Srvcs',
       'DME_Suplr_Sbmtd_Chrgs', 'DME_Suplr_Mdcr_Alowd_Amt',
       'DME_Suplr_Mdcr_Pymt_Amt', 'DME_Suplr_Mdcr_Stdzd_Pymt_Amt',
       'POS_Sprsn_Ind', 'POS_Tot_Suplrs', 'POS_Tot_Suplr_HCPCS_Cds',
       'POS_Tot_Suplr_Benes', 'POS_Tot_Suplr_Clms', 'POS_Tot_Suplr_Srvcs',
       'POS_Suplr_Sbmtd_Chrgs', 'POS_Suplr_Mdcr_Alowd_Amt',
       'POS_Suplr_Mdcr_Pymt_Amt', 'POS_Suplr_Mdcr_Stdzd_Pymt_Amt',
       'Drug_Tot_Suplrs', 'Drug_Tot_Suplr_HCPCS_Cds',
       'Drug_Tot_Suplr_Benes', 'Drug_Tot_Suplr_Clms',
       'Drug_Tot_Suplr_Srvcs', 'Drug_Suplr_Sbmtd_Chrgs',
       'Drug_Suplr_Mdcr_Alowd_Amt', 'Drug_Suplr_Mdcr_Pymt_Amt',
       'Drug_Suplr_Mdcr_Stdzd_Pymt_Amt', 'Bene_Avg_Age',
       'Fraud', 'FraudType']

In [4]:
df = df[cols]

In [5]:
df = df.drop(["Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [6]:
df

Rndrng_Prvdr_Crdntls  Rndrng_Prvdr_Gndr  Rndrng_Prvdr_Type  \
0                       7310                0.0                 39   
1                       9043                0.0                 24   
2                       4737                1.0                 39   
3                       7895                0.0                 91   
4                       9043                1.0                 24   
...                      ...                ...                ...   
334369                  9043                1.0                 39   
334370                  7310                0.0                 24   
334371                  3446                0.0                 39   
334372                  7310                1.0                 39   
334373                 17582                1.0                 39   

        Rndrng_Prvdr_Mdcr_Prtcptg_Ind  Tot_HCPCS_Cds  Tot_Benes_x  Tot_Srvcs  \
0                                   1           16.0        291.0      764.0   
1                                   1           34.0        251.0      660.0   
2                                   1           35.0        359.0     1400.0   
3                                   1           92.0        739.0     3916.0   
4                                   1           43.0        285.0      922.0   
...                               ...            ...          ...        ...   
334369                              1           37.0        365.0     2272.0   
334370                              1           50.0        138.0      769.0   
334371                              1           34.0       1215.0     6097.0   
334372                              1           40.0        333.0     1093.0   
334373                              1           15.0        407.0      884.0   

        Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  ...  \
0            402812.00            85319.63           69175.78  ...   
1            149315.45            49859.16           34786.35  ...   
2            238600.00           149023.89          114975.60  ...   
3            777162.00           277266.94          210439.56  ...   
4            139700.00            71391.30           52741.85  ...   
...                ...                 ...                ...  ...   
334369       587582.00           203150.57          157754.65  ...   
334370       109972.88            53888.01           40893.46  ...   
334371       696266.98           513866.65          390895.36  ...   
334372       182515.00            93505.14           68252.03  ...   
334373       340479.02            90924.61           74063.76  ...   

        Drug_Tot_Suplr_Benes  Drug_Tot_Suplr_Clms  Drug_Tot_Suplr_Srvcs  \
0                        0.0                  0.0                   0.0   
1                       17.0                 51.0                2002.0   
2                        0.0                  0.0                   0.0   
3                        0.0                  0.0                   0.0   
4                       11.0                 18.0                  18.0   
...                      ...                  ...                   ...   
334369                  11.0                 12.0                  12.0   
334370                  11.0                 15.0                2387.0   
334371                  16.0                 61.0                  61.0   
334372                   0.0                  0.0                   0.0   
334373                   0.0                  0.0                   0.0   

        Drug_Suplr_Sbmtd_Chrgs  Drug_Suplr_Mdcr_Alowd_Amt  \
0                         0.00                       0.00   
1                      7051.88                    2010.45   
2                         0.00                       0.00   
3                         0.00                       0.00   
4                       714.00                     594.00   
...                        ...                        ...   
334369                  462.00       

In [7]:
X = df.drop(['Fraud','FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6444629	total: 897ms	remaining: 7m 27s
1:	learn: 0.6005719	total: 1.68s	remaining: 6m 58s
2:	learn: 0.5605914	total: 2.58s	remaining: 7m 8s
3:	learn: 0.5241069	total: 3.34s	remaining: 6m 54s
4:	learn: 0.4906333	total: 4.15s	remaining: 6m 50s
5:	learn: 0.4598803	total: 4.99s	remaining: 6m 51s
6:	learn: 0.4315481	total: 5.86s	remaining: 6m 52s
7:	learn: 0.4053871	total: 6.68s	remaining: 6m 51s
8:	learn: 0.3811114	total: 7.56s	remaining: 6m 52s
9:	learn: 0.3586078	total: 8.38s	remaining: 6m 50s
10:	learn: 0.3376548	total: 9.31s	remaining: 6m 53s
11:	learn: 0.3181865	total: 10s	remaining: 6m 48s
12:	learn: 0.3000396	total: 10.9s	remaining: 6m 47s
13:	learn: 0.2831079	total: 11.8s	remaining: 6m 48s
14:	learn: 0.2672055	total: 12.5s	remaining: 6m 44s
15:	learn: 0.2523418	total: 13.2s	remaining: 6m 39s
16:	learn: 0.2385015	total: 14.2s	remaining: 6m 44s
17:	learn: 0.2255560	total: 15.1s	remaining: 6m 44s
18:	learn: 0.2133578	total: 15.9s	remaining: 6m 42s
19:	learn: 0.2018787	tota

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [8]:
df = pd.read_csv("../../labelled_data/combined/combined_rus_features.csv")

In [9]:
df = df.drop(["Unnamed: 0","Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [10]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6822169	total: 154ms	remaining: 1m 16s
1:	learn: 0.6716437	total: 308ms	remaining: 1m 16s
2:	learn: 0.6624516	total: 427ms	remaining: 1m 10s
3:	learn: 0.6543503	total: 540ms	remaining: 1m 6s
4:	learn: 0.6472799	total: 660ms	remaining: 1m 5s
5:	learn: 0.6411597	total: 797ms	remaining: 1m 5s
6:	learn: 0.6313988	total: 922ms	remaining: 1m 4s
7:	learn: 0.6230534	total: 952ms	remaining: 58.5s
8:	learn: 0.6151469	total: 1.12s	remaining: 1m 1s
9:	learn: 0.6091734	total: 1.23s	remaining: 1m
10:	learn: 0.6013802	total: 1.33s	remaining: 59.3s
11:	learn: 0.5937559	total: 1.49s	remaining: 1m
12:	learn: 0.5868433	total: 1.62s	remaining: 1m
13:	learn: 0.5814423	total: 1.71s	remaining: 59.2s
14:	learn: 0.5749508	total: 1.84s	remaining: 59.6s
15:	learn: 0.5699630	total: 1.99s	remaining: 1m
16:	learn: 0.5638682	total: 2.12s	remaining: 1m
17:	learn: 0.5581616	total: 2.2s	remaining: 59s
18:	learn: 0.5517586	total: 2.3s	remaining: 58.3s
19:	learn: 0.5455495	total: 2.47s	remaining: 59.3s
20:	le

In [11]:
df = pd.read_csv("../../labelled_data/combined/combined_ros_features.csv")

In [12]:
df = df.drop(["Unnamed: 0","Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [13]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6514469	total: 1.57s	remaining: 13m 4s
1:	learn: 0.6131925	total: 2.97s	remaining: 12m 19s
2:	learn: 0.5798374	total: 4.35s	remaining: 12m
3:	learn: 0.5486465	total: 5.82s	remaining: 12m 2s
4:	learn: 0.5172231	total: 7.18s	remaining: 11m 50s
5:	learn: 0.4896572	total: 8.7s	remaining: 11m 55s
6:	learn: 0.4637551	total: 9.98s	remaining: 11m 42s
7:	learn: 0.4387899	total: 11.2s	remaining: 11m 28s
8:	learn: 0.4174396	total: 12.3s	remaining: 11m 10s
9:	learn: 0.3964792	total: 13.5s	remaining: 11m 1s
10:	learn: 0.3784300	total: 14.6s	remaining: 10m 49s
11:	learn: 0.3607901	total: 15.7s	remaining: 10m 37s
12:	learn: 0.3426458	total: 16.9s	remaining: 10m 33s
13:	learn: 0.3260755	total: 18.1s	remaining: 10m 26s
14:	learn: 0.3108150	total: 19.3s	remaining: 10m 23s
15:	learn: 0.2974944	total: 20.4s	remaining: 10m 16s
16:	learn: 0.2832565	total: 21.6s	remaining: 10m 14s
17:	learn: 0.2713062	total: 22.7s	remaining: 10m 8s
18:	learn: 0.2596308	total: 23.9s	remaining: 10m 4s
19:	learn: 0.

In [14]:
df = pd.read_csv("../../labelled_data/combined/combined_smote_features.csv")

In [15]:
df = df.drop(["Unnamed: 0","Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [16]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6526009	total: 2.11s	remaining: 17m 35s
1:	learn: 0.6155817	total: 4.27s	remaining: 17m 42s
2:	learn: 0.5821306	total: 6.05s	remaining: 16m 42s
3:	learn: 0.5510170	total: 8.04s	remaining: 16m 37s
4:	learn: 0.5227902	total: 10.2s	remaining: 16m 46s
5:	learn: 0.4952990	total: 11.9s	remaining: 16m 23s
6:	learn: 0.4702732	total: 13.9s	remaining: 16m 19s
7:	learn: 0.4461858	total: 16.1s	remaining: 16m 28s
8:	learn: 0.4248362	total: 17.8s	remaining: 16m 11s
9:	learn: 0.4044452	total: 19.8s	remaining: 16m 10s
10:	learn: 0.3847434	total: 21.8s	remaining: 16m 8s
11:	learn: 0.3680426	total: 23.6s	remaining: 15m 59s
12:	learn: 0.3514681	total: 25.8s	remaining: 16m 4s
13:	learn: 0.3353391	total: 27.7s	remaining: 16m 1s
14:	learn: 0.3211058	total: 29.7s	remaining: 15m 59s
15:	learn: 0.3074795	total: 31.5s	remaining: 15m 53s
16:	learn: 0.2940480	total: 33.3s	remaining: 15m 47s
17:	learn: 0.2815128	total: 35.3s	remaining: 15m 45s
18:	learn: 0.2698233	total: 37.1s	remaining: 15m 38s
19:	le

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/Combined/imputed_combined.csv")
cols = ['Rndrng_Prvdr_Crdntls',
'Rndrng_Prvdr_Gndr', 
'Rndrng_Prvdr_Type',
'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 
'Tot_HCPCS_Cds', 
'Tot_Benes_x',
'Tot_Srvcs', 
'Tot_Sbmtd_Chrg', 
'Tot_Mdcr_Alowd_Amt',
'Tot_Mdcr_Pymt_Amt', 
'Tot_Mdcr_Stdzd_Amt', 
'Drug_Sprsn_Ind_x',
'Drug_Tot_HCPCS_Cds', 
'Drug_Tot_Benes', 
'Drug_Tot_Srvcs',
'Drug_Sbmtd_Chrg', 
'Drug_Mdcr_Alowd_Amt', 
'Drug_Mdcr_Pymt_Amt',
       'Drug_Mdcr_Stdzd_Amt', 'Med_Sprsn_Ind', 'Med_Tot_HCPCS_Cds',
       'Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
       'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',
       'Bene_Avg_Age_x', 'Bene_Age_LT_65_Cnt_x', 'Bene_Age_65_74_Cnt_x',
       'Bene_Age_75_84_Cnt_x', 'Bene_Age_GT_84_Cnt_x', 'Bene_Feml_Cnt_x',
       'Bene_Male_Cnt_x', 'Bene_Race_Wht_Cnt_x', 'Bene_Race_Black_Cnt_x',
       'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt_x',
       'Bene_Race_NatInd_Cnt', 'Bene_Race_Othr_Cnt_x', 'Bene_Dual_Cnt_x',
       'Bene_Ndual_Cnt_x', 'Bene_CC_AF_Pct_x', 'Bene_CC_Alzhmr_Pct_x',
       'Bene_CC_Asthma_Pct_x', 'Bene_CC_Cncr_Pct_x', 'Bene_CC_CHF_Pct_x',
       'Bene_CC_CKD_Pct_x', 'Bene_CC_COPD_Pct_x', 'Bene_CC_Dprssn_Pct_x',
       'Bene_CC_Dbts_Pct_x', 'Bene_CC_Hyplpdma_Pct_x',
       'Bene_CC_Hyprtnsn_Pct_x', 'Bene_CC_IHD_Pct_x', 'Bene_CC_Opo_Pct_x',
       'Bene_CC_RAOA_Pct_x', 'Bene_CC_Sz_Pct_x', 'Bene_CC_Strok_Pct_x',
       'Bene_Avg_Risk_Scre_x', 'Rndrng_NPI', 'Fraud_x', 'FraudType_x',
'Prscrbr_Crdntls',
       'Prscrbr_Type_src', 'Tot_Clms', 'Tot_30day_Fills',
       'Tot_Drug_Cst', 'Tot_Day_Suply', 'GE65_Sprsn_Flag',
       'GE65_Tot_Clms', 'GE65_Tot_30day_Fills', 'GE65_Tot_Drug_Cst',
       'GE65_Tot_Day_Suply', 'GE65_Bene_Sprsn_Flag', 'GE65_Tot_Benes',
       'Brnd_Sprsn_Flag', 'Brnd_Tot_Clms', 'Brnd_Tot_Drug_Cst',
       'Gnrc_Sprsn_Flag', 'Gnrc_Tot_Clms', 'Gnrc_Tot_Drug_Cst',
       'Othr_Sprsn_Flag', 'Othr_Tot_Clms', 'Othr_Tot_Drug_Cst',
       'MAPD_Sprsn_Flag', 'MAPD_Tot_Clms', 'MAPD_Tot_Drug_Cst',
       'PDP_Sprsn_Flag', 'PDP_Tot_Clms', 'PDP_Tot_Drug_Cst',
       'LIS_Sprsn_Flag', 'LIS_Tot_Clms', 'LIS_Drug_Cst',
       'NonLIS_Sprsn_Flag', 'NonLIS_Tot_Clms', 'NonLIS_Drug_Cst',
       'Opioid_Tot_Clms', 'Opioid_Tot_Drug_Cst', 'Opioid_Tot_Suply',
       'Opioid_Tot_Benes', 'Opioid_Prscrbr_Rate', 'Opioid_LA_Tot_Clms',
       'Opioid_LA_Tot_Drug_Cst', 'Opioid_LA_Tot_Suply',
       'Opioid_LA_Tot_Benes', 'Opioid_LA_Prscrbr_Rate', 'Antbtc_Tot_Clms',
       'Antbtc_Tot_Drug_Cst', 'Antbtc_Tot_Benes',
       'Antpsyct_GE65_Sprsn_Flag', 'Antpsyct_GE65_Tot_Clms',
       'Antpsyct_GE65_Tot_Drug_Cst', 'Antpsyct_GE65_Tot_Benes',
       'Bene_Race_Api_Cnt_x', 
       'Bene_Race_Natind_Cnt_x', 
       'Rfrg_Prvdr_Type_Flag', 'Tot_Suplrs', 'Tot_Suplr_HCPCS_Cds',
       'Tot_Suplr_Benes', 'Tot_Suplr_Clms', 'Tot_Suplr_Srvcs',
       'Suplr_Sbmtd_Chrgs', 'Suplr_Mdcr_Alowd_Amt', 'Suplr_Mdcr_Pymt_Amt',
       'Suplr_Mdcr_Stdzd_Pymt_Amt', 'DME_Sprsn_Ind', 'DME_Tot_Suplrs',
       'DME_Tot_Suplr_HCPCS_Cds', 'DME_Tot_Suplr_Benes',
       'DME_Tot_Suplr_Clms', 'DME_Tot_Suplr_Srvcs',
       'DME_Suplr_Sbmtd_Chrgs', 'DME_Suplr_Mdcr_Alowd_Amt',
       'DME_Suplr_Mdcr_Pymt_Amt', 'DME_Suplr_Mdcr_Stdzd_Pymt_Amt',
       'POS_Sprsn_Ind', 'POS_Tot_Suplrs', 'POS_Tot_Suplr_HCPCS_Cds',
       'POS_Tot_Suplr_Benes', 'POS_Tot_Suplr_Clms', 'POS_Tot_Suplr_Srvcs',
       'POS_Suplr_Sbmtd_Chrgs', 'POS_Suplr_Mdcr_Alowd_Amt',
       'POS_Suplr_Mdcr_Pymt_Amt', 'POS_Suplr_Mdcr_Stdzd_Pymt_Amt',
       'Drug_Tot_Suplrs', 'Drug_Tot_Suplr_HCPCS_Cds',
       'Drug_Tot_Suplr_Benes', 'Drug_Tot_Suplr_Clms',
       'Drug_Tot_Suplr_Srvcs', 'Drug_Suplr_Sbmtd_Chrgs',
       'Drug_Suplr_Mdcr_Alowd_Amt', 'Drug_Suplr_Mdcr_Pymt_Amt',
       'Drug_Suplr_Mdcr_Stdzd_Pymt_Amt', 'Bene_Avg_Age',
       'Fraud', 'FraudType']
df = df[cols]


In [3]:
df = df.drop(["Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [5]:
X = df.drop(['Fraud','FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 1.8665983	total: 1.55s	remaining: 6.21s
1:	learn: 1.6038835	total: 2.96s	remaining: 4.44s
2:	learn: 1.4119142	total: 4.44s	remaining: 2.96s
3:	learn: 1.2619998	total: 5.96s	remaining: 1.49s
4:	learn: 1.1392945	total: 7.53s	remaining: 0us
Accuracy: 0.9998953271028037

Confusion Matrix:
 [[66868     0     0     0     0]
 [    3     0     0     0     0]
 [    2     0     0     0     0]
 [    1     0     0     0     0]
 [    1     0     0     0     0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     66868
           1       0.00      0.00      0.00         3
           2       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1

    accuracy                           1.00     66875
   macro avg       0.20      0.20      0.20     66875
weighted avg       1.00      1.00      1.00     66875



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [11]:
df = pd.read_csv("../../labelled_data/combined/combined_rus_features.csv")

In [12]:
df = df.drop(["Unnamed: 0","Fraud_x","Rndrng_NPI",],axis=1)

In [13]:
X = df.drop(['FraudType_x'], axis=1)
y = df['FraudType_x']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 2.2846142	total: 195ms	remaining: 781ms
1:	learn: 2.2659605	total: 363ms	remaining: 545ms
2:	learn: 2.2493475	total: 555ms	remaining: 370ms
3:	learn: 2.2329180	total: 732ms	remaining: 183ms
4:	learn: 2.2087960	total: 900ms	remaining: 0us
Accuracy: 0.6086956521739131

Confusion Matrix:
 [[12  2  1  0  0  0]
 [ 0  1  1  1  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  1]
 [ 0  1  0  0  1  0]
 [ 1  0  0  0  1  0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.80      0.86        15
           1       0.25      0.33      0.29         3
           3       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         1
          10       0.50      0.50      0.50         2
          11       0.00      0.00      0.00         2

    accuracy                           0.61        23
   macro avg       0.28      0.27      0.27        23
weighted avg       0.68      0.61      0.64        23



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start,

In [15]:
df = pd.read_csv("../../labelled_data/combined/combined_ros_features.csv")

In [16]:
df = df.drop(["Unnamed: 0","Fraud_x","Rndrng_NPI",],axis=1)

In [17]:
X = df.drop(['FraudType_x'], axis=1)
y = df['FraudType_x']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 1.8797705	total: 2.49s	remaining: 9.96s
1:	learn: 1.6129730	total: 5.15s	remaining: 7.72s
2:	learn: 1.4288380	total: 7.61s	remaining: 5.08s
3:	learn: 1.2758065	total: 10.3s	remaining: 2.57s
4:	learn: 1.1566469	total: 13s	remaining: 0us
Accuracy: 1.0

Confusion Matrix:
 [[66792     0     0     0     0     0     0     0     0     0]
 [    0 22831     0     0     0     0     0     0     0     0]
 [    0     0  7111     0     0     0     0     0     0     0]
 [    0     0     0  1183     0     0     0     0     0     0]
 [    0     0     0     0  1197     0     0     0     0     0]
 [    0     0     0     0     0  3536     0     0     0     0]
 [    0     0     0     0     0     0  1194     0     0     0]
 [    0     0     0     0     0     0     0  7043     0     0]
 [    0     0     0     0     0     0     0     0 16790     0]
 [    0     0     0     0     0     0     0     0     0  6051]]

Classification Report:
               precision    recall  f1-score   support

         