In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/DMEPOS/imputed_dmepos.csv")

In [3]:
df = df.drop(["Unnamed: 0","Rfrg_NPI"],axis=1)

In [4]:
df

Rfrg_Prvdr_Crdntls  Rfrg_Prvdr_Gndr  Rfrg_Prvdr_Type  \
0                     2362              0.0               44   
1                     3017              0.0               26   
2                     1629              1.0               44   
3                     2684              0.0              117   
4                     4511              1.0               87   
...                    ...              ...              ...   
383452                3017              1.0               44   
383453                2362              0.0               26   
383454                1186              0.0               44   
383455                2362              1.0               44   
383456                5465              1.0               44   

        Rfrg_Prvdr_Type_Flag  Tot_Suplrs  Tot_Suplr_HCPCS_Cds  \
0                        1.0           8                    7   
1                        1.0          28                   47   
2                        1.0          11                   44   
3                        1.0           5                   12   
4                        1.0           1                    1   
...                      ...         ...                  ...   
383452                   1.0          35                   67   
383453                   1.0          12                   17   
383454                   1.0          47                   56   
383455                   1.0          11                   27   
383456                   1.0           6                    8   

        Tot_Suplr_Benes  Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  \
0                  11.0             132              159           29869.97   
1                  33.0              97             1136           44435.62   
2                  19.0              65             1117           18711.69   
3                  23.0              29             4778           26951.30   
4                  13.0              13               13            2080.00   
...                 ...             ...              ...                ...   
383452             46.0             180             4981          107216.47   
383453             11.0              35              384           11429.84   
383454             86.0             502            11743          173452.58   
383455             14.0              55              322           19471.42   
383456             13.0              38               55            6707.76   

        ...  Bene_CC_Hyplpdma_Pct  Bene_CC_Hyprtnsn_Pct  Bene_CC_IHD_Pct  \
0       ...                  0.75                  0.75             0.32   
1       ...                  0.73                  0.75             0.39   
2       ...                  0.74                  0.75             0.53   
3       ...                  0.54                  0.69             0.48   
4       ...                  0.75                  0.75             0.00   
...     ...                   ...                   ...              ...   
383452  ...                  0.75                  0.75             0.50   
383453  ...                  0.75                  0.75             0.00   
383454  ...                  0.60                  0.73             0.66   
383455  ...                  0.75                  0.75             0.35   
383456  ...                  0.75                  0.75             0.00   

        Bene_CC_Opo_Pct  Bene_CC_RAOA_Pct  Bene_CC_Sz_Pct  Bene_CC_Strok_Pct  \
0                  0.00              0.64             0.0               0.00   
1                  0.00              0.58             0.0               0.00   
2                  0.00              0.68             0.0               0.00   
3                  0.00              0.75             0.0               0.00   
4                  0.00              0.75             0.0               0.00   
...                 ...               ...             ...                ...   
383452             0.40             

In [5]:
X = df.drop(['Fraud','FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6446535	total: 544ms	remaining: 4m 31s
1:	learn: 0.6006962	total: 865ms	remaining: 3m 35s
2:	learn: 0.5606318	total: 1.34s	remaining: 3m 42s
3:	learn: 0.5242046	total: 1.72s	remaining: 3m 32s
4:	learn: 0.4907765	total: 2.12s	remaining: 3m 29s
5:	learn: 0.4599780	total: 2.59s	remaining: 3m 33s
6:	learn: 0.4316295	total: 2.93s	remaining: 3m 26s
7:	learn: 0.4053825	total: 3.36s	remaining: 3m 26s
8:	learn: 0.3811245	total: 3.72s	remaining: 3m 22s
9:	learn: 0.3585939	total: 4.12s	remaining: 3m 21s
10:	learn: 0.3377230	total: 4.51s	remaining: 3m 20s
11:	learn: 0.3182776	total: 4.87s	remaining: 3m 17s
12:	learn: 0.3000892	total: 5.25s	remaining: 3m 16s
13:	learn: 0.2831257	total: 5.58s	remaining: 3m 13s
14:	learn: 0.2672604	total: 6s	remaining: 3m 14s
15:	learn: 0.2523944	total: 6.34s	remaining: 3m 11s
16:	learn: 0.2384763	total: 6.8s	remaining: 3m 13s
17:	learn: 0.2254432	total: 7.11s	remaining: 3m 10s
18:	learn: 0.2131850	total: 7.46s	remaining: 3m 8s
19:	learn: 0.2016893	total:

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [6]:
df = pd.read_csv("../../labelled_data/DMEPOS/dmepos_rus_features.csv")

In [7]:
df = df.drop(["Unnamed: 0.1","Unnamed: 0","Rfrg_NPI"],axis=1)

In [8]:
df

Rfrg_Prvdr_Crdntls  Rfrg_Prvdr_Gndr  Rfrg_Prvdr_Type  \
0                  4437              1.0               65   
1                  1997              1.0               65   
2                  4587              0.0               87   
3                   419              1.0               65   
4                  2362              0.0               30   
..                  ...              ...              ...   
199                3017              0.0               26   
200                2362              0.0               29   
201                3017              0.0               26   
202                3017              0.0               29   
203                3017              0.0               44   

     Rfrg_Prvdr_Type_Flag  Tot_Suplrs  Tot_Suplr_HCPCS_Cds  Tot_Suplr_Benes  \
0                     1.0           2                   10             16.0   
1                     1.0           6                   22             42.0   
2                     1.0           5                    9             18.0   
3                     1.0           5                    7             25.0   
4                     1.0          12                   18            112.0   
..                    ...         ...                  ...              ...   
199                   1.0          19                   22             20.0   
200                   1.0           4                   16             13.0   
201                   1.0           1                    1             17.0   
202                   0.0          14                   18             61.0   
203                   1.0           2                    3             20.0   

     Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  ...  \
0                18               41            4202.72  ...   
1               220              324           53997.47  ...   
2                34              172            6297.83  ...   
3                32             1503            8361.72  ...   
4               372            96088          437064.15  ...   
..              ...              ...                ...  ...   
199              58             2584           21190.91  ...   
200              44              468            5537.80  ...   
201              12               12             929.52  ...   
202              84              491           44971.91  ...   
203              15               26            1651.46  ...   

     Bene_CC_Dbts_Pct  Bene_CC_Hyplpdma_Pct  Bene_CC_Hyprtnsn_Pct  \
0                0.75                  0.75                  0.75   
1                0.60                  0.75                  0.75   
2                0.70                  0.61                  0.73   
3                0.56                  0.69                  0.59   
4                0.70                  0.63                  0.75   
..                ...                   ...                   ...   
199              0.75                  0.70                  0.75   
200              0.42                  0.65                  0.75   
201              0.75                  0.69                  0.75   
202              0.46                  0.57                  0.75   
203              0.55                  0.69                  0.75   

     Bene_CC_IHD_Pct  Bene_CC_Opo_Pct  Bene_CC_RAOA_Pct  Bene_CC_Sz_Pct  \
0               0.75             0.00              0.72             0.0   
1               0.67             0.20              0.69             0.0   
2               0.64             0.00              0.64             0.0   
3               0.63             0.00              0.50             0.0   
4               0.61             0.21              0.23             0.0   
..               ...              ...               ...             ...   
199             0.55             0.00              0.56             0.0   
200             0.21             0.00              0.40             0.0   
201             0.53             0.00             

In [9]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6859936	total: 86.9ms	remaining: 43.4s
1:	learn: 0.6767634	total: 182ms	remaining: 45.3s
2:	learn: 0.6706037	total: 284ms	remaining: 47.1s
3:	learn: 0.6605775	total: 375ms	remaining: 46.5s
4:	learn: 0.6525874	total: 468ms	remaining: 46.3s
5:	learn: 0.6454960	total: 550ms	remaining: 45.3s
6:	learn: 0.6386224	total: 621ms	remaining: 43.7s
7:	learn: 0.6319520	total: 680ms	remaining: 41.8s
8:	learn: 0.6250081	total: 768ms	remaining: 41.9s
9:	learn: 0.6210773	total: 840ms	remaining: 41.2s
10:	learn: 0.6142555	total: 909ms	remaining: 40.4s
11:	learn: 0.6082572	total: 1.01s	remaining: 41.2s
12:	learn: 0.6032054	total: 1.09s	remaining: 40.9s
13:	learn: 0.5977951	total: 1.17s	remaining: 40.7s
14:	learn: 0.5922840	total: 1.28s	remaining: 41.3s
15:	learn: 0.5863956	total: 1.34s	remaining: 40.4s
16:	learn: 0.5812775	total: 1.46s	remaining: 41.5s
17:	learn: 0.5757718	total: 1.57s	remaining: 42s
18:	learn: 0.5698619	total: 1.6s	remaining: 40.6s
19:	learn: 0.5646718	total: 1.69s	remaining

In [10]:
df = pd.read_csv("../../labelled_data/DMEPOS/dmepos_ros_features.csv")

In [11]:
df = df.drop(["Unnamed: 0.1","Unnamed: 0","Rfrg_NPI"],axis=1)

In [12]:
df

Rfrg_Prvdr_Crdntls  Rfrg_Prvdr_Gndr  Rfrg_Prvdr_Type  \
0                     2362              0.0               44   
1                     3017              0.0               26   
2                     1629              1.0               44   
3                     2684              0.0              117   
4                     4511              1.0               87   
...                    ...              ...              ...   
766705                3017              0.0               26   
766706                3017              0.0               44   
766707                1186              1.0               26   
766708                3017              0.0               85   
766709                4277              1.0               65   

        Rfrg_Prvdr_Type_Flag  Tot_Suplrs  Tot_Suplr_HCPCS_Cds  \
0                        1.0           8                    7   
1                        1.0          28                   47   
2                        1.0          11                   44   
3                        1.0           5                   12   
4                        1.0           1                    1   
...                      ...         ...                  ...   
766705                   1.0           4                   11   
766706                   1.0           1                    5   
766707                   1.0           9                   27   
766708                   1.0           9                   18   
766709                   1.0           7                    7   

        Tot_Suplr_Benes  Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  \
0                  11.0             132              159           29869.97   
1                  33.0              97             1136           44435.62   
2                  19.0              65             1117           18711.69   
3                  23.0              29             4778           26951.30   
4                  13.0              13               13            2080.00   
...                 ...             ...              ...                ...   
766705             20.0              20             1499           10756.06   
766706             11.0              35               58            8610.00   
766707             11.0              38              527           24189.32   
766708             20.0             197              256           24346.83   
766709             32.0              57            10044           49465.56   

        ...  Bene_CC_Dbts_Pct  Bene_CC_Hyplpdma_Pct  Bene_CC_Hyprtnsn_Pct  \
0       ...              0.75                  0.75                  0.75   
1       ...              0.75                  0.73                  0.75   
2       ...              0.68                  0.74                  0.75   
3       ...              0.64                  0.54                  0.69   
4       ...              0.00                  0.75                  0.75   
...     ...               ...                   ...                   ...   
766705  ...              0.44                  0.63                  0.75   
766706  ...              0.58                  0.75                  0.75   
766707  ...              0.41                  0.50                  0.75   
766708  ...              0.64                  0.65                  0.75   
766709  ...              0.35                  0.48                  0.75   

        Bene_CC_IHD_Pct  Bene_CC_Opo_Pct  Bene_CC_RAOA_Pct  Bene_CC_Sz_Pct  \
0                  0.32              0.0              0.64             0.0   
1                  0.39              0.0              0.58             0.0   
2                  0.53              0.0              0.68             0.0   
3                  0.48              0.0              0.75             0.0   
4                  0.00              0.0              0.75             0.0   
...                 ...              ...               ...             ...   
766705             0.54              0

In [13]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6616602	total: 1.2s	remaining: 9m 56s
1:	learn: 0.6335599	total: 2.23s	remaining: 9m 15s
2:	learn: 0.6082929	total: 3.33s	remaining: 9m 12s
3:	learn: 0.5829178	total: 4.37s	remaining: 9m 1s
4:	learn: 0.5649450	total: 5.51s	remaining: 9m 5s
5:	learn: 0.5468845	total: 6.74s	remaining: 9m 14s
6:	learn: 0.5279374	total: 7.87s	remaining: 9m 13s
7:	learn: 0.5144493	total: 9.04s	remaining: 9m 16s
8:	learn: 0.4971225	total: 10.2s	remaining: 9m 15s
9:	learn: 0.4818705	total: 11.3s	remaining: 9m 11s
10:	learn: 0.4662931	total: 12.4s	remaining: 9m 10s
11:	learn: 0.4532774	total: 13.5s	remaining: 9m 7s
12:	learn: 0.4414301	total: 14.5s	remaining: 9m 2s
13:	learn: 0.4286940	total: 15.6s	remaining: 9m
14:	learn: 0.4162445	total: 16.7s	remaining: 8m 58s
15:	learn: 0.4037990	total: 17.6s	remaining: 8m 53s
16:	learn: 0.3923053	total: 18.7s	remaining: 8m 52s
17:	learn: 0.3811886	total: 19.9s	remaining: 8m 52s
18:	learn: 0.3730914	total: 20.9s	remaining: 8m 49s
19:	learn: 0.3654816	total: 21.

In [14]:
df = pd.read_csv("../../labelled_data/DMEPOS/dmepos_smote_features.csv")

In [15]:
df = df.drop(["Unnamed: 0.1","Unnamed: 0","Rfrg_NPI"],axis=1)

In [16]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6557283	total: 1.12s	remaining: 9m 18s
1:	learn: 0.6225825	total: 2.23s	remaining: 9m 14s
2:	learn: 0.5924241	total: 3.48s	remaining: 9m 36s
3:	learn: 0.5656682	total: 4.53s	remaining: 9m 22s
4:	learn: 0.5372390	total: 5.63s	remaining: 9m 17s
5:	learn: 0.5136950	total: 6.9s	remaining: 9m 28s
6:	learn: 0.4884111	total: 7.91s	remaining: 9m 16s
7:	learn: 0.4656611	total: 9.06s	remaining: 9m 17s
8:	learn: 0.4450625	total: 10.2s	remaining: 9m 17s
9:	learn: 0.4274337	total: 11.3s	remaining: 9m 12s
10:	learn: 0.4102172	total: 12.4s	remaining: 9m 12s
11:	learn: 0.3936229	total: 13.5s	remaining: 9m 10s
12:	learn: 0.3779130	total: 14.6s	remaining: 9m 8s
13:	learn: 0.3615233	total: 15.8s	remaining: 9m 9s
14:	learn: 0.3488430	total: 16.9s	remaining: 9m 5s
15:	learn: 0.3342742	total: 18s	remaining: 9m 5s
16:	learn: 0.3214344	total: 19.2s	remaining: 9m 6s
17:	learn: 0.3097549	total: 20.3s	remaining: 9m 3s
18:	learn: 0.2984430	total: 21.5s	remaining: 9m 5s
19:	learn: 0.2882828	total: 22.7

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/DMEPOS/imputed_dmepos.csv")

In [3]:
df = df.drop(["Unnamed: 0","Rfrg_NPI"],axis=1)

In [6]:
X = df.drop(['Fraud','FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 1.8727472	total: 1.26s	remaining: 5.06s
1:	learn: 1.6072748	total: 2.43s	remaining: 3.64s
2:	learn: 1.4135769	total: 3.73s	remaining: 2.49s
3:	learn: 1.2637592	total: 5s	remaining: 1.25s
4:	learn: 1.1411076	total: 6.29s	remaining: 0us
Accuracy: 0.9997131382673551

Confusion Matrix:
 [[76670     0     0     0     0     0     0     0     0]
 [    2     0     0     0     0     0     0     0     0]
 [    3     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0]
 [    6     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0]
 [    7     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     76670
           1       0.00      0.00      0.00         2
    

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [7]:
df = pd.read_csv("../../labelled_data/DMEPOS/dmepos_ros_type_features.csv")

In [10]:
df = df.drop(["Unnamed: 0","Unnamed: 0.1","Rfrg_NPI"],axis=1)

In [12]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 2.0325532	total: 13.4s	remaining: 53.6s
1:	learn: 1.7634606	total: 27.6s	remaining: 41.4s
2:	learn: 1.5655964	total: 40s	remaining: 26.6s
3:	learn: 1.4137308	total: 53.2s	remaining: 13.3s
4:	learn: 1.2939533	total: 1m 5s	remaining: 0us
Accuracy: 0.9590944069169213

Confusion Matrix:
 [[50837  6129  3476   893    12  2257    15  5953    23  6025  1112]
 [    0 71626  2428  2277     0     0     0     0     0     0     0]
 [    0     0 76525     0     0     0     0     0     0     0     0]
 [    0     0     0 76611     0     0     0     0     0     0     0]
 [    0     0     0     0 76495     0     0     0     0     0     0]
 [    0     0     0     0     0 76716     0     0     0     0     0]
 [    0     0     0     0     0     0 76760     0     0     0     0]
 [    0  3899     0     0     0     0     0 73237     0     0     0]
 [    0     0     0     0     0     0     0     0 76692     0     0]
 [    0     0     0     0     0     0     0     0     0 76738     0]
 [    0     0  

In [2]:
df = pd.read_csv("../../labelled_data/DMEPOS/dmepos_ros_type_features.csv")

In [3]:
df = df.drop(["Unnamed: 0","Unnamed: 0.1","Rfrg_NPI"],axis=1)

In [4]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 2.0325532	total: 13.1s	remaining: 52.3s
1:	learn: 1.7634606	total: 24.9s	remaining: 37.4s
2:	learn: 1.5655964	total: 38s	remaining: 25.3s
3:	learn: 1.4137308	total: 51.1s	remaining: 12.8s
4:	learn: 1.2939533	total: 1m 4s	remaining: 0us
Accuracy: 0.9590944069169213

Confusion Matrix:
 [[50837  6129  3476   893    12  2257    15  5953    23  6025  1112]
 [    0 71626  2428  2277     0     0     0     0     0     0     0]
 [    0     0 76525     0     0     0     0     0     0     0     0]
 [    0     0     0 76611     0     0     0     0     0     0     0]
 [    0     0     0     0 76495     0     0     0     0     0     0]
 [    0     0     0     0     0 76716     0     0     0     0     0]
 [    0     0     0     0     0     0 76760     0     0     0     0]
 [    0  3899     0     0     0     0     0 73237     0     0     0]
 [    0     0     0     0     0     0     0     0 76692     0     0]
 [    0     0     0     0     0     0     0     0     0 76738     0]
 [    0     0  