In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/part_D/imputed_partd.csv")

In [3]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI"],axis=1)

In [4]:
df

Prscrbr_Crdntls  Prscrbr_Gndr  Prscrbr_Type  Prscrbr_Type_src  \
0                   7632           0.0            86               1.0   
1                   7632           0.0             9               1.0   
2                   4394           0.0            42               1.0   
3                   3535           1.0            42               1.0   
4                   6421           1.0           120               1.0   
...                  ...           ...           ...               ...   
1254982            13080           1.0           128               1.0   
1254983             4831           0.0            42               1.0   
1254984            15356           0.0           120               1.0   
1254985             7632           0.0           137               1.0   
1254986            16837           1.0            86               1.0   

         Tot_Clms  Tot_30day_Fills  Tot_Drug_Cst  Tot_Day_Suply  Tot_Benes  \
0           324.0       369.800000      20606.08         8621.0      106.0   
1          1992.0      2145.666667      79803.65        60953.0      228.0   
2            57.0        57.700000        327.34          554.0       43.0   
3            18.0        18.000000        128.52          181.0       16.0   
4            37.0        47.000000       3834.98         1366.0       17.0   
...           ...              ...           ...            ...        ...   
1254982      40.0        80.666667       9870.01         2357.0       17.0   
1254983      72.0        73.200000        397.84         1092.0       27.0   
1254984      47.0        90.466667      13618.96         2704.0       21.0   
1254985     249.0       291.066667      10899.52         5801.0      126.0   
1254986     274.0       290.633333      14449.86         6436.0      103.0   

         GE65_Sprsn_Flag  ...  Bene_Race_Black_Cnt  Bene_Race_Api_Cnt  \
0                    1.0  ...                 27.0                0.0   
1                    1.0  ...                 81.0                0.0   
2                    1.0  ...                  0.0                0.0   
3                    1.0  ...                  0.0                0.0   
4                    1.0  ...                  0.0                0.0   
...                  ...  ...                  ...                ...   
1254982              1.0  ...                  0.0               16.0   
1254983              1.0  ...                 18.0               18.0   
1254984              1.0  ...                  0.0                0.0   
1254985              1.0  ...                 14.0               16.0   
1254986              1.0  ...                 25.0                0.0   

         Bene_Race_Hspnc_Cnt  Bene_Race_Natind_Cnt  Bene_Race_Othr_Cnt  \
0                       13.0                   0.0                 0.0   
1                       12.0                   0.0                 0.0   
2                        0.0                   0.0                 0.0   
3                        0.0                   0.0                 0.0   
4                        0.0                   0.0                 0.0   
...                      ...                   ...                 ...   
1254982                  0.0                   0.0                 0.0   
1254983                  0.0                   0.0                 0.0   
1254984                  0.0                   0.0                 0.0   
1254985                 18.0                   0.0                14.0   
1254986                 16.0                   0.0                 0.0   

         Bene_Dual_Cnt  Bene_Ndual_Cnt  Bene_Avg_Risk_Scre  Fraud  FraudType  
0                 28.0            78.0            2.245800      0          0  
1                125.0           103.0            1.695165      0          0  
2                  0.0            43.0            1.006070      0          0  
3                  0.0            12.0            1.251869      0          0  
4                 11.0

In [5]:
X = df.drop(['Fraud','FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6444903	total: 535ms	remaining: 4m 27s
1:	learn: 0.6004851	total: 1.01s	remaining: 4m 11s
2:	learn: 0.5604357	total: 1.45s	remaining: 4m
3:	learn: 0.5238871	total: 1.9s	remaining: 3m 55s
4:	learn: 0.4903923	total: 2.41s	remaining: 3m 58s
5:	learn: 0.4595992	total: 2.88s	remaining: 3m 57s
6:	learn: 0.4312502	total: 3.33s	remaining: 3m 54s
7:	learn: 0.4050210	total: 3.79s	remaining: 3m 53s
8:	learn: 0.3807265	total: 4.13s	remaining: 3m 45s
9:	learn: 0.3581974	total: 4.58s	remaining: 3m 44s
10:	learn: 0.3372642	total: 5.02s	remaining: 3m 43s
11:	learn: 0.3177828	total: 5.48s	remaining: 3m 42s
12:	learn: 0.2996312	total: 5.93s	remaining: 3m 42s
13:	learn: 0.2826616	total: 6.38s	remaining: 3m 41s
14:	learn: 0.2668008	total: 6.82s	remaining: 3m 40s
15:	learn: 0.2519531	total: 7.3s	remaining: 3m 40s
16:	learn: 0.2380412	total: 7.75s	remaining: 3m 40s
17:	learn: 0.2250093	total: 8.23s	remaining: 3m 40s
18:	learn: 0.2127674	total: 8.71s	remaining: 3m 40s
19:	learn: 0.2012680	total: 

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.9997649383660427

Confusion Matrix:
 [[250939      0]
 [    59      0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    250939
           1       0.00      0.00      0.00        59

    accuracy                           1.00    250998
   macro avg       0.50      0.50      0.50    250998
weighted avg       1.00      1.00      1.00    250998



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [6]:
df = pd.read_csv("../../labelled_data/part_D/partd_rus_features.csv")

In [7]:
df = df.drop(["Unnamed: 0","Unnamed: 0.1","PRSCRBR_NPI"],axis=1)

In [8]:
df

Prscrbr_Crdntls  Prscrbr_Gndr  Prscrbr_Type  Prscrbr_Type_src  Tot_Clms  \
0               2929           1.0           120               1.0    1132.0   
1               4394           0.0           131               1.0     201.0   
2               5885           0.0            86               1.0    7058.0   
3               9176           0.0            64               1.0     186.0   
4               1060           1.0           120               1.0      54.0   
..               ...           ...           ...               ...       ...   
579             7632           0.0            63               1.0     263.0   
580             5885           0.0            60               1.0     813.0   
581             7632           0.0            63               0.0    1040.0   
582             9176           0.0            86               1.0    2132.0   
583            15356           0.0           120               1.0      47.0   

     Tot_30day_Fills  Tot_Drug_Cst  Tot_Day_Suply  Tot_Benes  GE65_Sprsn_Flag  \
0        1191.566667      71404.48        25695.0      103.0              1.0   
1         203.400000       2945.42         1641.0       77.0              1.0   
2       14652.966667     841439.84       428631.0      413.0              1.0   
3         244.000000       4984.06         4018.0      105.0              1.0   
4          96.000000       2551.76         2813.0       17.0              1.0   
..               ...           ...            ...        ...              ...   
579       423.600000      66723.17        12370.0       55.0              1.0   
580      1618.800000      56694.66        45859.0       85.0              1.0   
581      2311.366667     100240.86        67529.0      122.0              1.0   
582      2296.933333    1444745.29        64849.0       90.0              1.0   
583        90.466667      13618.96         2704.0       21.0              1.0   

     ...  Bene_Race_Wht_Cnt  Bene_Race_Black_Cnt  Bene_Race_Api_Cnt  \
0    ...               97.0                  0.0                0.0   
1    ...               69.0                 20.0                0.0   
2    ...              338.0                 38.0                0.0   
3    ...               80.0                 17.0                0.0   
4    ...               13.0                  0.0                0.0   
..   ...                ...                  ...                ...   
579  ...               39.0                 38.0               35.0   
580  ...              100.0                 23.0               27.0   
581  ...               44.0                 30.0                0.0   
582  ...               59.0                 11.0               15.0   
583  ...               16.0                  0.0                0.0   

     Bene_Race_Hspnc_Cnt  Bene_Race_Natind_Cnt  Bene_Race_Othr_Cnt  \
0                    0.0                  30.0                 0.0   
1                    0.0                   0.0                 0.0   
2                   28.0                   0.0                11.0   
3                    0.0                   0.0                 0.0   
4                    0.0                   0.0                 0.0   
..                   ...                   ...                 ...   
579                 14.0                   0.0                 0.0   
580                 23.0                   0.0                14.0   
581                105.0                   0.0                 0.0   
582                 15.0                   0.0                14.0   
583                  0.0                   0.0                 0.0   

     Bene_Dual_Cnt  Bene_Ndual_Cnt  Bene_Avg_Risk_Scre  Fraud  
0             37.0            66.0            1.488790      0  
1             13.0            80.0            1.040951      0  
2            116.0           297.0            1.375367      0  
3             32.0            73.0            1.393905      0  
4              0.0            17.0            1.222294   

In [9]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6869508	total: 116ms	remaining: 57.9s
1:	learn: 0.6786844	total: 224ms	remaining: 55.7s
2:	learn: 0.6734361	total: 319ms	remaining: 52.9s
3:	learn: 0.6676917	total: 437ms	remaining: 54.2s
4:	learn: 0.6572535	total: 549ms	remaining: 54.4s
5:	learn: 0.6497610	total: 665ms	remaining: 54.7s
6:	learn: 0.6423041	total: 770ms	remaining: 54.2s
7:	learn: 0.6358433	total: 898ms	remaining: 55.2s
8:	learn: 0.6298912	total: 1.02s	remaining: 55.8s
9:	learn: 0.6228520	total: 1.15s	remaining: 56.4s
10:	learn: 0.6180515	total: 1.22s	remaining: 54.2s
11:	learn: 0.6115049	total: 1.34s	remaining: 54.7s
12:	learn: 0.6062372	total: 1.44s	remaining: 53.9s
13:	learn: 0.6024180	total: 1.55s	remaining: 53.7s
14:	learn: 0.5970721	total: 1.65s	remaining: 53.4s
15:	learn: 0.5908110	total: 1.78s	remaining: 53.8s
16:	learn: 0.5845684	total: 1.9s	remaining: 53.9s
17:	learn: 0.5786400	total: 1.99s	remaining: 53.4s
18:	learn: 0.5734863	total: 2.08s	remaining: 52.5s
19:	learn: 0.5693084	total: 2.22s	remainin

In [10]:
df = pd.read_csv("../../labelled_data/part_D/partd_ros_features.csv")

In [11]:
df = df.drop(["Unnamed: 0","Unnamed: 0.1","PRSCRBR_NPI"],axis=1)

In [12]:
df

Prscrbr_Crdntls  Prscrbr_Gndr  Prscrbr_Type  Prscrbr_Type_src  \
0                   7632           0.0            86               1.0   
1                   7632           0.0             9               1.0   
2                   4394           0.0            42               1.0   
3                   3535           1.0            42               1.0   
4                   6421           1.0           120               1.0   
...                  ...           ...           ...               ...   
2509385             9176           0.0            86               1.0   
2509386             9176           0.0            60               1.0   
2509387             9176           0.0            60               1.0   
2509388             7632           0.0            86               1.0   
2509389            13776           0.0           155               1.0   

         Tot_Clms  Tot_30day_Fills  Tot_Drug_Cst  Tot_Day_Suply  Tot_Benes  \
0           324.0       369.800000      20606.08         8621.0      106.0   
1          1992.0      2145.666667      79803.65        60953.0      228.0   
2            57.0        57.700000        327.34          554.0       43.0   
3            18.0        18.000000        128.52          181.0       16.0   
4            37.0        47.000000       3834.98         1366.0       17.0   
...           ...              ...           ...            ...        ...   
2509385    6364.0     11801.166667     478117.79       342993.0      312.0   
2509386    5599.0     10111.033333     538281.10       296379.0      444.0   
2509387     106.0       109.333333       3824.90         3195.0       33.0   
2509388     959.0      1501.533333     107461.83        40631.0      134.0   
2509389      27.0        51.000000        843.81         1212.0       12.0   

         GE65_Sprsn_Flag  ...  Bene_Race_Wht_Cnt  Bene_Race_Black_Cnt  \
0                    1.0  ...               67.0                 27.0   
1                    1.0  ...              130.0                 81.0   
2                    1.0  ...               41.0                  0.0   
3                    1.0  ...               12.0                  0.0   
4                    1.0  ...               12.0                  0.0   
...                  ...  ...                ...                  ...   
2509385              1.0  ...              236.0                 41.0   
2509386              1.0  ...              393.0                 66.0   
2509387              1.0  ...               33.0                  0.0   
2509388              1.0  ...               53.0                 18.0   
2509389              1.0  ...               12.0                  0.0   

         Bene_Race_Api_Cnt  Bene_Race_Hspnc_Cnt  Bene_Race_Natind_Cnt  \
0                      0.0                 13.0                   0.0   
1                      0.0                 12.0                   0.0   
2                      0.0                  0.0                   0.0   
3                      0.0                  0.0                   0.0   
4                      0.0                  0.0                   0.0   
...                    ...                  ...                   ...   
2509385                0.0                 22.0                   0.0   
2509386               13.0                 32.0                   0.0   
2509387                0.0                  0.0                   0.0   
2509388               14.0                 42.0                   0.0   
2509389                0.0                  0.0                   0.0   

         Bene_Race_Othr_Cnt  Bene_Dual_Cnt  Bene_Ndual_Cnt  \
0                       0.0           28.0            78.0   
1                       0.0          125.0           103.0   
2                       0.0            0.0            43.0   
3                       0.0            0.0            12.0   
4                       0.0           11.0            11.0   
...                     ...            ...             ..

In [13]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6684962	total: 3s	remaining: 24m 56s
1:	learn: 0.6476746	total: 5.94s	remaining: 24m 40s
2:	learn: 0.6284672	total: 8.55s	remaining: 23m 36s
3:	learn: 0.6095824	total: 11.3s	remaining: 23m 21s
4:	learn: 0.5920936	total: 14.1s	remaining: 23m 15s
5:	learn: 0.5752369	total: 16.9s	remaining: 23m 14s
6:	learn: 0.5587521	total: 19.8s	remaining: 23m 17s
7:	learn: 0.5435766	total: 22.6s	remaining: 23m 7s
8:	learn: 0.5301650	total: 25.3s	remaining: 23m 1s
9:	learn: 0.5156660	total: 28.1s	remaining: 22m 57s
10:	learn: 0.5023003	total: 30.8s	remaining: 22m 50s
11:	learn: 0.4908825	total: 33.7s	remaining: 22m 51s
12:	learn: 0.4808997	total: 36.5s	remaining: 22m 48s
13:	learn: 0.4703135	total: 39.2s	remaining: 22m 42s
14:	learn: 0.4595995	total: 42.2s	remaining: 22m 43s
15:	learn: 0.4498469	total: 44.9s	remaining: 22m 39s
16:	learn: 0.4400028	total: 47.8s	remaining: 22m 38s
17:	learn: 0.4299621	total: 50.5s	remaining: 22m 32s
18:	learn: 0.4221375	total: 53.5s	remaining: 22m 33s
19:	lear

In [14]:
df = pd.read_csv("../../labelled_data/part_D/partd_smote_features.csv")

In [15]:
df = df.drop(["Unnamed: 0","Unnamed: 0.1","PRSCRBR_NPI"],axis=1)

In [16]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 0.6532906	total: 2.51s	remaining: 20m 52s
1:	learn: 0.6188030	total: 4.94s	remaining: 20m 30s
2:	learn: 0.5852241	total: 7.35s	remaining: 20m 18s
3:	learn: 0.5544856	total: 9.64s	remaining: 19m 54s
4:	learn: 0.5260465	total: 11.9s	remaining: 19m 39s
5:	learn: 0.4999350	total: 14s	remaining: 19m 14s
6:	learn: 0.4757150	total: 15.4s	remaining: 18m 1s
7:	learn: 0.4520191	total: 16.6s	remaining: 16m 59s
8:	learn: 0.4311870	total: 17.9s	remaining: 16m 15s
9:	learn: 0.4099012	total: 19.1s	remaining: 15m 37s
10:	learn: 0.3905223	total: 20.4s	remaining: 15m 6s
11:	learn: 0.3733039	total: 21.6s	remaining: 14m 40s
12:	learn: 0.3571030	total: 22.8s	remaining: 14m 15s
13:	learn: 0.3408753	total: 24s	remaining: 13m 54s
14:	learn: 0.3262648	total: 25.3s	remaining: 13m 37s
15:	learn: 0.3125327	total: 26.5s	remaining: 13m 22s
16:	learn: 0.2991384	total: 27.8s	remaining: 13m 8s
17:	learn: 0.2869120	total: 29s	remaining: 12m 56s
18:	learn: 0.2755689	total: 30.2s	remaining: 12m 45s
19:	learn: 0

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/part_D/imputed_partd.csv")

In [3]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI"],axis=1)

In [4]:
X = df.drop(['Fraud','FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 2.0124007	total: 3.66s	remaining: 14.6s
1:	learn: 1.6990359	total: 7.82s	remaining: 11.7s
2:	learn: 1.4821639	total: 11.6s	remaining: 7.75s
3:	learn: 1.3170938	total: 14.6s	remaining: 3.65s
4:	learn: 1.1844165	total: 17.9s	remaining: 0us
Accuracy: 0.9997649383660427

Confusion Matrix:
 [[250939      0      0      0      0      0      0      0      0]
 [    18      0      0      0      0      0      0      0      0]
 [     3      0      0      0      0      0      0      0      0]
 [     3      0      0      0      0      0      0      0      0]
 [     9      0      0      0      0      0      0      0      0]
 [     9      0      0      0      0      0      0      0      0]
 [     2      0      0      0      0      0      0      0      0]
 [    13      0      0      0      0      0      0      0      0]
 [     2      0      0      0      0      0      0      0      0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00     

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [5]:
df = pd.read_csv("../../labelled_data/part_D/partd_rus_type_features.csv")

In [6]:
df = df.drop(["Unnamed: 0","Unnamed: 0.1","PRSCRBR_NPI"],axis=1)

In [10]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=5, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

0:	learn: 2.3838753	total: 17.6ms	remaining: 70.6ms
1:	learn: 2.3726585	total: 21.4ms	remaining: 32.1ms
2:	learn: 2.3583830	total: 34.9ms	remaining: 23.3ms
3:	learn: 2.3451491	total: 38.4ms	remaining: 9.59ms
4:	learn: 2.3309701	total: 51.5ms	remaining: 0us
Accuracy: 0.0

Confusion Matrix:
 [[0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       1.0
          11       0.00      0.00      0.00       1.0
          12       0.00      0.00      0.00       0.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modi

In [ ]:
df = pd.read_csv("../../labelled_data/part_D/partd_ros_type_features.csv")

In [ ]:
df = df.drop(["Unnamed: 0","Unnamed: 0.1","PRSCRBR_NPI"],axis=1)

In [ ]:
df

Prscrbr_Crdntls  Prscrbr_Gndr  Prscrbr_Type  Prscrbr_Type_src  \
0                    7632           0.0            86               1.0   
1                    7632           0.0             9               1.0   
2                    4394           0.0            42               1.0   
3                    3535           1.0            42               1.0   
4                    6421           1.0           120               1.0   
...                   ...           ...           ...               ...   
17565725             6109           1.0           158               1.0   
17565726             6109           1.0           158               1.0   
17565727             6109           1.0           158               1.0   
17565728             6109           1.0           158               1.0   
17565729             6109           1.0           158               1.0   

          Tot_Clms  Tot_30day_Fills  Tot_Drug_Cst  Tot_Day_Suply  Tot_Benes  \
0            324.0       369.800000      20606.08         8621.0      106.0   
1           1992.0      2145.666667      79803.65        60953.0      228.0   
2             57.0        57.700000        327.34          554.0       43.0   
3             18.0        18.000000        128.52          181.0       16.0   
4             37.0        47.000000       3834.98         1366.0       17.0   
...            ...              ...           ...            ...        ...   
17565725     167.0       206.000000      14205.65         4626.0       78.0   
17565726     167.0       206.000000      14205.65         4626.0       78.0   
17565727     167.0       206.000000      14205.65         4626.0       78.0   
17565728     167.0       206.000000      14205.65         4626.0       78.0   
17565729     167.0       206.000000      14205.65         4626.0       78.0   

          GE65_Sprsn_Flag  ...  Bene_Race_Wht_Cnt  Bene_Race_Black_Cnt  \
0                     1.0  ...               67.0                 27.0   
1                     1.0  ...              130.0                 81.0   
2                     1.0  ...               41.0                  0.0   
3                     1.0  ...               12.0                  0.0   
4                     1.0  ...               12.0                  0.0   
...                   ...  ...                ...                  ...   
17565725              1.0  ...               54.0                 22.0   
17565726              1.0  ...               54.0                 22.0   
17565727              1.0  ...               54.0                 22.0   
17565728              1.0  ...               54.0                 22.0   
17565729              1.0  ...               54.0                 22.0   

          Bene_Race_Api_Cnt  Bene_Race_Hspnc_Cnt  Bene_Race_Natind_Cnt  \
0                       0.0                 13.0                   0.0   
1                       0.0                 12.0                   0.0   
2                       0.0                  0.0                   0.0   
3                       0.0                  0.0                   0.0   
4                       0.0                  0.0                   0.0   
...                     ...                  ...                   ...   
17565725                0.0                  0.0                   0.0   
17565726                0.0                  0.0                   0.0   
17565727                0.0                  0.0                   0.0   
17565728                0.0                  0.0                   0.0   
17565729                0.0                  0.0                   0.0   

          Bene_Race_Othr_Cnt  Bene_Dual_Cnt  Bene_Ndual_Cnt  \
0                        0.0           28.0            78.0   
1                        0.0          125.0           103.0   
2                        0.0            0.0            43.0   
3                        0.0            0.0            12.0   
4                        0.0           11.0            11.0   
... 

In [ ]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a CatBoost Classifier
model = CatBoostClassifier(iterations=3, depth=10, learning_rate=0.05, loss_function='MultiClass', random_seed=42)

# Train the model
model.fit(X_train, y_train, cat_features=None)  # You can specify categorical features if needed

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

: 