In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
df = pd.read_csv("../../labelled_data/part_B/imputed_partb.csv")

In [5]:
df = df.drop(["Unnamed: 0","Rndrng_NPI"],axis=1)

In [6]:
df

Rndrng_Prvdr_Crdntls  Rndrng_Prvdr_Gndr  Rndrng_Prvdr_Type  \
0                        7310                0.0                 39   
1                        7310                0.0                 65   
2                        7310                0.0                  5   
3                        7310                1.0                 56   
4                        9043                0.0                 27   
...                       ...                ...                ...   
1100721                  7310                0.0                 22   
1100722                  7310                1.0                 39   
1100723                  3073                0.0                 13   
1100724                  7310                0.0                 63   
1100725                 17582                1.0                 39   

         Rndrng_Prvdr_Mdcr_Prtcptg_Ind  Tot_HCPCS_Cds  Tot_Benes  Tot_Srvcs  \
0                                    1           16.0      291.0      764.0   
1                                    1           18.0     2633.0     5930.0   
2                                    1           54.0      167.0     2003.0   
3                                    1           21.0       56.0      571.0   
4                                    1           30.0       89.0      125.0   
...                                ...            ...        ...        ...   
1100721                              1            9.0      155.0      171.0   
1100722                              1           40.0      333.0     1093.0   
1100723                              1            2.0       66.0      415.0   
1100724                              1           46.0      456.0      851.0   
1100725                              1           15.0      407.0      884.0   

         Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  ...  \
0             402812.00            85319.63           69175.78  ...   
1             915291.00           227372.53          176497.74  ...   
2             182532.48           101757.15           76938.82  ...   
3              23680.00             9011.99            7224.35  ...   
4             152154.00            30631.10           23962.85  ...   
...                 ...                 ...                ...  ...   
1100721       329504.00            32266.94           25803.90  ...   
1100722       182515.00            93505.14           68252.03  ...   
1100723        20985.00            16171.02           11759.42  ...   
1100724       304460.56           113283.09           85463.83  ...   
1100725       340479.02            90924.61           74063.76  ...   

         Bene_CC_Hyplpdma_Pct  Bene_CC_Hyprtnsn_Pct  Bene_CC_IHD_Pct  \
0                        73.0                  75.0             66.0   
1                        48.0                  48.0             24.0   
2                        52.0                  68.0             31.0   
3                        52.0                  50.0             23.0   
4                        43.0                  60.0             33.0   
...                       ...                   ...              ...   
1100721                  71.0                  75.0             70.0   
1100722                  49.0                  66.0             25.0   
1100723                  61.0                  53.0             26.0   
1100724                  44.0                  53.0             26.0   
1100725                  75.0                  75.0             61.0   

         Bene_CC_Opo_Pct  Bene_CC_RAOA_Pct  Bene_CC_Sz_Pct  Bene_CC_Strok_Pct  \
0                   11.0              51.0             9.0               19.0   
1                   10.0              38.0             1.0                3.0   
2                    6.0              75.0            10.0                5.0   
3                   20.0              32.0             0.0                0.0   
4                   13.0              57.0             7.0                8.0   
...

In [7]:
X = df.drop(['Fraud', 'FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Convert the data to DMatrix format for XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Set hyperparameters for the XGBoost model
params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'max_depth': 3,
    'eta': 0.1,
    'subsample': 0.8,
}

# Train the XGBoost model
num_round = 100
model = xgb.train(params, dtrain, num_round)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Convert predicted probabilities to binary predictions
y_pred = [1 if pred > 0.5 else 0 for pred in y_pred]

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.9999091511996584

Confusion Matrix:
 [[220126      0]
 [    20      0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    220126
           1       0.00      0.00      0.00        20

    accuracy                           1.00    220146
   macro avg       0.50      0.50      0.50    220146
weighted avg       1.00      1.00      1.00    220146



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
df = pd.read_csv("../../labelled_data/part_B/partb_rus_features.csv")

In [9]:
df = df.drop(["Unnamed: 0"],axis=1)

In [10]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Convert the data to DMatrix format for XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Set hyperparameters for the XGBoost model
params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'max_depth': 3,
    'eta': 0.1,
    'subsample': 0.8,
}

# Train the XGBoost model
num_round = 100
model = xgb.train(params, dtrain, num_round)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Convert predicted probabilities to binary predictions
y_pred = [1 if pred > 0.5 else 0 for pred in y_pred]

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.723404255319149

Confusion Matrix:
 [[16  4]
 [ 9 18]]

Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.80      0.71        20
           1       0.82      0.67      0.73        27

    accuracy                           0.72        47
   macro avg       0.73      0.73      0.72        47
weighted avg       0.74      0.72      0.72        47



In [11]:
df = pd.read_csv("../../labelled_data/part_B/partb_ros_features.csv")

In [12]:
df = df.drop(["Unnamed: 0"],axis=1)

In [13]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Convert the data to DMatrix format for XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Set hyperparameters for the XGBoost model
params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'max_depth': 3,
    'eta': 0.1,
    'subsample': 0.8,
}

# Train the XGBoost model
num_round = 100
model = xgb.train(params, dtrain, num_round)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Convert predicted probabilities to binary predictions
y_pred = [1 if pred > 0.5 else 0 for pred in y_pred]

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.9594588455492863

Confusion Matrix:
 [[202412  17848]
 [     0 219984]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.92      0.96    220260
           1       0.92      1.00      0.96    219984

    accuracy                           0.96    440244
   macro avg       0.96      0.96      0.96    440244
weighted avg       0.96      0.96      0.96    440244



In [14]:
df = pd.read_csv("../../labelled_data/part_B/partb_smote_features.csv")

In [15]:
df = df.drop(["Unnamed: 0"],axis=1)

In [16]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Convert the data to DMatrix format for XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Set hyperparameters for the XGBoost model
params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'max_depth': 3,
    'eta': 0.1,
    'subsample': 0.8,
}

# Train the XGBoost model
num_round = 100
model = xgb.train(params, dtrain, num_round)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Convert predicted probabilities to binary predictions
y_pred = [1 if pred > 0.5 else 0 for pred in y_pred]

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.9692838760312478

Confusion Matrix:
 [[208077   9977]
 [  3486 216764]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.95      0.97    218054
           1       0.96      0.98      0.97    220250

    accuracy                           0.97    438304
   macro avg       0.97      0.97      0.97    438304
weighted avg       0.97      0.97      0.97    438304



In [17]:
df = pd.read_csv("../../labelled_data/part_B/partb_rus_type_features.csv")

In [18]:
df = df.drop(["Unnamed: 0"],axis=1)

In [20]:

# Assuming df is your DataFrame containing the data

X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert the data to DMatrix format for XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Set hyperparameters for the XGBoost model
params = {
    'objective': 'multi:softprob',
    'eval_metric': 'mlogloss',  # Use 'mlogloss' for multi-class problems
    'max_depth': 3,
    'eta': 0.1,
    'subsample': 0.8,
    'num_class': len(pd.unique(y)),  # Specify the number of classes
}

# Train the XGBoost model
num_round = 100
model = xgb.train(params, dtrain, num_round)

# Make predictions on the test set
y_pred_prob = model.predict(dtest)
y_pred = np.argmax(y_pred_prob, axis=1)  # Convert probabilities to class labels

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)


Accuracy: 0.0

Confusion Matrix:
 [[0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           5       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       1.0
          11       0.00      0.00      0.00       1.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modi

In [2]:
df = pd.read_csv("../../labelled_data/part_B/partb_ros_type_features.csv")

In [3]:
df = df.drop(["Unnamed: 0"],axis=1)

In [4]:

# Assuming df is your DataFrame containing the data

X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert the data to DMatrix format for XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Set hyperparameters for the XGBoost model
params = {
    'objective': 'multi:softprob',
    'eval_metric': 'mlogloss',  # Use 'mlogloss' for multi-class problems
    'max_depth': 3,
    'eta': 0.1,
    'subsample': 0.8,
    'num_class': len(pd.unique(y)),  # Specify the number of classes
}

# Train the XGBoost model
num_round = 100
model = xgb.train(params, dtrain, num_round)

# Make predictions on the test set
y_pred_prob = model.predict(dtest)
y_pred = np.argmax(y_pred_prob, axis=1)  # Convert probabilities to class labels

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)


Accuracy: 0.9966448675664474

Confusion Matrix:
 [[210905   2631    592      0     43    192      0   1382     55      0
    4539    167      0]
 [     0 219923      0      0      0      0      0      0      0      0
       0      0      0]
 [     0      0 220160      0      0      0      0      0      0      0
       0      0      0]
 [     0      0      0 219441      0      0      0      0      0      0
       0      0      0]
 [     0      0      0      0 219881      0      0      0      0      0
       0      0      0]
 [     0      0      0      0      0 220554      0      0      0      0
       0      0      0]
 [     0      0      0      0      0      0 220506      0      0      0
       0      0      0]
 [     0      0      0      0      0      0      0 219980      0      0
       0      0      0]
 [     0      0      0      0      0      0      0      0 219640      0
       0      0      0]
 [     0      0      0      0      0      0      0      0      0 220210
       0      0

: 