In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/DMEPOS/features/dmepos_features_data.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230782 entries, 0 to 230781
Data columns (total 14 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   Unnamed: 0                 230782 non-null  int64  
 1   Rfrg_NPI                   230782 non-null  int64  
 2   Rfrg_Prvdr_Type            230782 non-null  object 
 3   Rfrg_Prvdr_Gndr            230782 non-null  object 
 4   Tot_Suplrs                 230782 non-null  int64  
 5   Tot_Suplr_Benes            230782 non-null  float64
 6   Tot_Suplr_Clms             230782 non-null  int64  
 7   Tot_Suplr_Srvcs            230782 non-null  int64  
 8   Suplr_Sbmtd_Chrgs          230782 non-null  float64
 9   Suplr_Mdcr_Alowd_Amt       230782 non-null  float64
 10  Suplr_Mdcr_Pymt_Amt        230782 non-null  float64
 11  Suplr_Mdcr_Stdzd_Pymt_Amt  230782 non-null  float64
 12  Fraud                      230782 non-null  int64  
 13  FraudType                  23

In [4]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Rfrg_Prvdr_Type'] = label_encoder.fit_transform(df['Rfrg_Prvdr_Type'])

In [5]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Rfrg_Prvdr_Gndr'] = label_encoder.fit_transform(df['Rfrg_Prvdr_Gndr'])

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['FraudType'] = label_encoder.fit_transform(df['FraudType'])

In [7]:
df = df.drop(["Unnamed: 0","Rfrg_NPI"],axis=1)

In [8]:
df

Rfrg_Prvdr_Type  Rfrg_Prvdr_Gndr  Tot_Suplrs  Tot_Suplr_Benes  \
0                    21                1          28             33.0   
1                    37                0          11             19.0   
2                    71                0           1             13.0   
3                    21                0          37             50.0   
4                    63                1           2             11.0   
...                 ...              ...         ...              ...   
230777               21                1          29             40.0   
230778               37                0          35             46.0   
230779               21                1          12             11.0   
230780               37                1          47             86.0   
230781               37                0          11             14.0   

        Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  \
0                   97             1136           44435.62   
1                   65             1117           18711.69   
2                   13               13            2080.00   
3                  237             6038           59451.27   
4                   11               11           20196.05   
...                ...              ...                ...   
230777             172             9523           67775.23   
230778             180             4981          107216.47   
230779              35              384           11429.84   
230780             502            11743          173452.58   
230781              55              322           19471.42   

        Suplr_Mdcr_Alowd_Amt  Suplr_Mdcr_Pymt_Amt  Suplr_Mdcr_Stdzd_Pymt_Amt  \
0                   21935.41             17189.84                   16974.70   
1                    7082.11              5577.12                    5955.41   
2                    1422.75              1134.81                    1173.77   
3                   19356.10             14444.34                   14379.62   
4                   11254.08              8628.40                    8512.72   
...                      ...                  ...                        ...   
230777              36981.87             28567.97                   27482.12   
230778              36070.78             28209.50                   28090.39   
230779               3530.96              2628.15                    2772.76   
230780              45053.58             34539.16                   35875.48   
230781               6386.75              4794.00                    5296.16   

        Fraud  FraudType  
0           0          0  
1           0          0  
2           0          0  
3           0          0  
4           0          0  
...       ...        ...  
230777      0          0  
230778      0          0  
230779      0          0  
230780      0          0  
230781      0          0  

[230782 rows x 12 columns]

In [10]:
X = df.drop(['Fraud', 'FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.999761682951665

Confusion Matrix:
 [[46146     0]
 [   11     0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     46146
           1       0.00      0.00      0.00        11

    accuracy                           1.00     46157
   macro avg       0.50      0.50      0.50     46157
weighted avg       1.00      1.00      1.00     46157



/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-sc

In [11]:
df = pd.read_csv("../../labelled_data/part_D/features/partd_rus_features.csv")

In [12]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI","Unnamed: 0.1"],axis=1)

In [13]:
df

Prscrbr_Type_src  Tot_Benes  Tot_Clms  Tot_30day_Fills  Tot_Day_Suply  \
0                   0      170.0       535       676.100000          13627   
1                   0       31.0        64        64.333333           1464   
2                   0       15.0        18        18.000000            145   
3                   0       12.0        17        17.000000            215   
4                   0      293.0      1130      1857.500000          48945   
..                ...        ...       ...              ...            ...   
383                 0      413.0      1330      3068.500000          91567   
384                 0       55.0       263       423.600000          12370   
385                 1      122.0      1040      2311.366667          67529   
386                 0       90.0      2132      2296.933333          64849   
387                 0       21.0        47        90.466667           2704   

     Tot_Drug_Cst  Fraud  
0        12162.93      0  
1         3055.64      0  
2           93.56      0  
3          407.47      0  
4       129441.19      0  
..            ...    ...  
383      89058.19      1  
384      66723.17      1  
385     100240.86      1  
386    1444745.29      1  
387      13618.96      1  

[388 rows x 7 columns]

In [14]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.41025641025641024

Confusion Matrix:
 [[13 35]
 [11 19]]

Classification Report:
               precision    recall  f1-score   support

           0       0.54      0.27      0.36        48
           1       0.35      0.63      0.45        30

    accuracy                           0.41        78
   macro avg       0.45      0.45      0.41        78
weighted avg       0.47      0.41      0.40        78



In [15]:
df = pd.read_csv("../../labelled_data/DMEPOS/features/dmepos_ros_features.csv")

In [16]:
df = df.drop(["Unnamed: 0","Rfrg_NPI","Unnamed: 0.1"],axis=1)

In [17]:
df

Rfrg_Prvdr_Type  Rfrg_Prvdr_Gndr  Tot_Suplrs  Tot_Suplr_Benes  \
0                    21                1          28             33.0   
1                    37                0          11             19.0   
2                    71                0           1             13.0   
3                    21                0          37             50.0   
4                    63                1           2             11.0   
...                 ...              ...         ...              ...   
415297               74                1           4             37.0   
415298               37                1          14             14.0   
415299               21                1          54            123.0   
415300               21                1           9             11.0   
415301               37                1          12             14.0   

        Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  \
0                   97             1136           44435.62   
1                   65             1117           18711.69   
2                   13               13            2080.00   
3                  237             6038           59451.27   
4                   11               11           20196.05   
...                ...              ...                ...   
415297              44             2274           53240.14   
415298              75              268           66324.45   
415299             693            24986          357044.65   
415300              28               95            4486.81   
415301              31              354           45507.46   

        Suplr_Mdcr_Alowd_Amt  Suplr_Mdcr_Pymt_Amt  Suplr_Mdcr_Stdzd_Pymt_Amt  \
0                   21935.41             17189.84                   16974.70   
1                    7082.11              5577.12                    5955.41   
2                    1422.75              1134.81                    1173.77   
3                   19356.10             14444.34                   14379.62   
4                   11254.08              8628.40                    8512.72   
...                      ...                  ...                        ...   
415297              26109.12             20332.82                   20107.73   
415298              15128.03             11551.37                   13283.37   
415299             146546.29            112854.65                  102817.87   
415300               1684.29              1329.77                    1343.25   
415301              21039.72             15759.50                   16153.53   

        Fraud  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
415297      1  
415298      1  
415299      1  
415300      1  
415301      1  

[415302 rows x 11 columns]

In [18]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.5868939694923009

Confusion Matrix:
 [[37100  4589]
 [29724 11648]]

Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.89      0.68     41689
           1       0.72      0.28      0.40     41372

    accuracy                           0.59     83061
   macro avg       0.64      0.59      0.54     83061
weighted avg       0.64      0.59      0.54     83061



In [19]:
df = pd.read_csv("../../labelled_data/DMEPOS/features/dmepos_smote_features.csv")

In [21]:
df = df.drop(["Unnamed: 0","Rfrg_NPI","Unnamed: 0.1"],axis=1)

In [22]:
df

Rfrg_Prvdr_Type  Rfrg_Prvdr_Gndr  Tot_Suplrs  Tot_Suplr_Benes  \
0                    21                1          28        33.000000   
1                    37                0          11        19.000000   
2                    71                0           1        13.000000   
3                    21                0          37        50.000000   
4                    63                1           2        11.000000   
...                 ...              ...         ...              ...   
395777               21                1          12        24.188160   
395778               44                1          19        43.579825   
395779               29                0          42        96.242597   
395780               62                1           5        13.326495   
395781               37                1          12        14.797126   

        Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  \
0                   97             1136       44435.620000   
1                   65             1117       18711.690000   
2                   13               13        2080.000000   
3                  237             6038       59451.270000   
4                   11               11       20196.050000   
...                ...              ...                ...   
395777             148            20606       59813.315571   
395778             297             4973       99946.708510   
395779             549            19240      275591.087813   
395780              33              113       58974.791561   
395781              35              659       46490.973593   

        Suplr_Mdcr_Alowd_Amt  Suplr_Mdcr_Pymt_Amt  Suplr_Mdcr_Stdzd_Pymt_Amt  \
0               21935.410000         17189.840000               16974.700000   
1                7082.110000          5577.120000                5955.410000   
2                1422.750000          1134.810000                1173.770000   
3               19356.100000         14444.340000               14379.620000   
4               11254.080000          8628.400000                8512.720000   
...                      ...                  ...                        ...   
395777          27500.847126         20441.371801               22565.285487   
395778          37387.317388         29121.468818               25598.683602   
395779         112608.731051         86792.777682               79431.194906   
395780          17496.538766         13608.490403               14013.860402   
395781          21248.041912         15939.383729               16367.696293   

        Fraud  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
395777      1  
395778      1  
395779      1  
395780      1  
395781      1  

[395782 rows x 11 columns]

In [23]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.6067814596308602

Confusion Matrix:
 [[33902  5020]
 [26106 14129]]

Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.87      0.69     38922
           1       0.74      0.35      0.48     40235

    accuracy                           0.61     79157
   macro avg       0.65      0.61      0.58     79157
weighted avg       0.65      0.61      0.58     79157



In [24]:
df = pd.read_csv("../../labelled_data/DMEPOS/features/dmepos_rus_type_features.csv")

In [25]:
df = df.drop(["Unnamed: 0","Rfrg_NPI","Unnamed: 0.1"],axis=1)

In [26]:
df

Rfrg_Prvdr_Type  Rfrg_Prvdr_Gndr  Tot_Suplrs  Tot_Suplr_Benes  \
0               35                0           9             16.0   
1               21                1          14             24.0   
2               37                0          50            177.0   
3               21                1          27             56.0   
4               21                0           9             11.0   
5               69                1           9             20.0   
6               21                1          11             25.0   
7               24                1          14             61.0   
8               82                1          13             21.0   
9               21                1          54            123.0   

   Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  Suplr_Mdcr_Alowd_Amt  \
0             100              570           75839.07              29240.75   
1              55              524           13977.96               6233.96   
2             889             8389          249763.07              83059.76   
3             283             4541           65681.20              24033.45   
4              38              527           24189.32              14730.75   
5             197              256           24346.83               7887.12   
6              41              961           29960.37               9621.23   
7              84              491           44971.91              14099.07   
8              52              201           49449.09              36611.92   
9             693            24986          357044.65             146546.29   

   Suplr_Mdcr_Pymt_Amt  Suplr_Mdcr_Stdzd_Pymt_Amt  FraudType  
0             22753.02                   21732.75          0  
1              4657.49                    3798.11          1  
2             64767.18                   71254.98          2  
3             18284.37                   16836.73          3  
4             11557.86                   11501.76          4  
5              5482.04                    5288.42          5  
6              5663.88                    5224.16          6  
7              8614.25                    5649.95          7  
8             28786.44                   26908.81          8  
9            112854.65                  102817.87          9

In [27]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=423)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.0

Confusion Matrix:
 [[0 0 0 1]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]]

Classification Report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           8       0.00      0.00      0.00       1.0
           9       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0



/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score

In [28]:
df = pd.read_csv("../../labelled_data/DMEPOS/features/dmepos_ros_type_features.csv")

In [29]:
df = df.drop(["Unnamed: 0","Rfrg_NPI","Unnamed: 0.1"],axis=1)

In [30]:
df

Rfrg_Prvdr_Type  Rfrg_Prvdr_Gndr  Tot_Suplrs  Tot_Suplr_Benes  \
0                     21                1          28             33.0   
1                     37                0          11             19.0   
2                     71                0           1             13.0   
3                     21                0          37             50.0   
4                     63                1           2             11.0   
...                  ...              ...         ...              ...   
2076505               94                1           7             62.0   
2076506               55                1          13             20.0   
2076507                5                1          11             13.0   
2076508               55                1          13             20.0   
2076509               21                1          10             11.0   

         Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  \
0                    97             1136           44435.62   
1                    65             1117           18711.69   
2                    13               13            2080.00   
3                   237             6038           59451.27   
4                    11               11           20196.05   
...                 ...              ...                ...   
2076505             188            60294          276182.10   
2076506             118             8251          169949.48   
2076507              69              193           22999.40   
2076508             118             8251          169949.48   
2076509              24             6862           70620.19   

         Suplr_Mdcr_Alowd_Amt  Suplr_Mdcr_Pymt_Amt  Suplr_Mdcr_Stdzd_Pymt_Amt  \
0                    21935.41             17189.84                   16974.70   
1                     7082.11              5577.12                    5955.41   
2                     1422.75              1134.81                    1173.77   
3                    19356.10             14444.34                   14379.62   
4                    11254.08              8628.40                    8512.72   
...                       ...                  ...                        ...   
2076505             251381.90            197822.48                  221558.76   
2076506              55170.86             43330.09                   42689.01   
2076507               9144.17              7141.38                    5899.57   
2076508              55170.86             43330.09                   42689.01   
2076509               5755.75              4147.03                    3221.35   

         FraudType  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
2076505          9  
2076506          9  
2076507          9  
2076508          9  
2076509          9  

[2076510 rows x 11 columns]

In [31]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=423)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.25609074841922264

Confusion Matrix:
 [[ 5048  5585 13780  2583   170   258  5831  1238   379  6533]
 [    0  9691  7303     0     0     0  7216  4943     0 12321]
 [ 6890     0 27868     0     0     0     0     0     0  6858]
 [    0     0     0     0     0     0     0     0     0 41682]
 [    0     0 41396     0     0     0     0     0     0     0]
 [    0     0     0 20830     0     0 20625     0     0     0]
 [    0  6997  6941     0     0     0 13894  6937     0  6941]
 [    0     0     0     0     0     0     0 41509     0     0]
 [ 2855  5937 11879     0     0     0  3016     0     0 17638]
 [ 8347  8279     0  8467     0     0  8292     0     0  8345]]

Classification Report:
               precision    recall  f1-score   support

           0       0.22      0.12      0.16     41405
           1       0.27      0.23      0.25     41474
           2       0.26      0.67      0.37     41616
           3       0.00      0.00      0.00     41682
           4       0.00