In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/part_D/features/partd_features_data.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1112168 entries, 0 to 1112167
Data columns (total 10 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   Unnamed: 0        1112168 non-null  int64  
 1   PRSCRBR_NPI       1112168 non-null  int64  
 2   Prscrbr_Type_src  1112168 non-null  object 
 3   Tot_Benes         1112168 non-null  float64
 4   Tot_Clms          1112168 non-null  int64  
 5   Tot_30day_Fills   1112168 non-null  float64
 6   Tot_Day_Suply     1112168 non-null  int64  
 7   Tot_Drug_Cst      1112168 non-null  float64
 8   Fraud             1112168 non-null  int64  
 9   FraudType         1112168 non-null  object 
dtypes: float64(3), int64(5), object(2)
memory usage: 84.9+ MB


In [5]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Prscrbr_Type_src'] = label_encoder.fit_transform(df['Prscrbr_Type_src'])

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['FraudType'] = label_encoder.fit_transform(df['FraudType'])

In [7]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI"],axis=1)

In [8]:
df

Prscrbr_Type_src  Tot_Benes  Tot_Clms  Tot_30day_Fills  \
0                       0      106.0       324       369.800000   
1                       0      228.0      1992      2145.666667   
2                       0       43.0        57        57.700000   
3                       0       67.0       218       404.933333   
4                       0       26.0        48        76.466667   
...                   ...        ...       ...              ...   
1112163                 0       17.0        40        80.666667   
1112164                 0       27.0        72        73.200000   
1112165                 0       21.0        47        90.466667   
1112166                 0      126.0       249       291.066667   
1112167                 0      103.0       274       290.633333   

         Tot_Day_Suply  Tot_Drug_Cst  Fraud  FraudType  
0                 8621      20606.08      0          0  
1                60953      79803.65      0          0  
2                  554        327.34      0          0  
3                10242      19778.34      0          0  
4                 1929       7416.39      0          0  
...                ...           ...    ...        ...  
1112163           2357       9870.01      0          0  
1112164           1092        397.84      0          0  
1112165           2704      13618.96      1          2  
1112166           5801      10899.52      0          0  
1112167           6436      14449.86      0          0  

[1112168 rows x 8 columns]

In [9]:
df['Prscrbr_Type_src'].value_counts()

0    1008148
1     104020
Name: Prscrbr_Type_src, dtype: int64

In [10]:
X = df.drop(['Fraud', 'FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.9997797099364306

Confusion Matrix:
 [[222385      2]
 [    47      0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    222387
           1       0.00      0.00      0.00        47

    accuracy                           1.00    222434
   macro avg       0.50      0.50      0.50    222434
weighted avg       1.00      1.00      1.00    222434



In [11]:
df = pd.read_csv("../../labelled_data/part_D/features/partd_rus_features.csv")

In [13]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI","Unnamed: 0.1"],axis=1)

In [14]:
df

Prscrbr_Type_src  Tot_Benes  Tot_Clms  Tot_30day_Fills  Tot_Day_Suply  \
0                   0      170.0       535       676.100000          13627   
1                   0       31.0        64        64.333333           1464   
2                   0       15.0        18        18.000000            145   
3                   0       12.0        17        17.000000            215   
4                   0      293.0      1130      1857.500000          48945   
..                ...        ...       ...              ...            ...   
383                 0      413.0      1330      3068.500000          91567   
384                 0       55.0       263       423.600000          12370   
385                 1      122.0      1040      2311.366667          67529   
386                 0       90.0      2132      2296.933333          64849   
387                 0       21.0        47        90.466667           2704   

     Tot_Drug_Cst  Fraud  
0        12162.93      0  
1         3055.64      0  
2           93.56      0  
3          407.47      0  
4       129441.19      0  
..            ...    ...  
383      89058.19      1  
384      66723.17      1  
385     100240.86      1  
386    1444745.29      1  
387      13618.96      1  

[388 rows x 7 columns]

In [15]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.41025641025641024

Confusion Matrix:
 [[13 35]
 [11 19]]

Classification Report:
               precision    recall  f1-score   support

           0       0.54      0.27      0.36        48
           1       0.35      0.63      0.45        30

    accuracy                           0.41        78
   macro avg       0.45      0.45      0.41        78
weighted avg       0.47      0.41      0.40        78



In [16]:
df = pd.read_csv("../../labelled_data/part_D/features/partd_ros_features.csv")

In [17]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI","Unnamed: 0.1"],axis=1)

In [18]:
df

Prscrbr_Type_src  Tot_Benes  Tot_Clms  Tot_30day_Fills  \
0                       0      106.0       324       369.800000   
1                       0      228.0      1992      2145.666667   
2                       0       43.0        57        57.700000   
3                       0       67.0       218       404.933333   
4                       0       26.0        48        76.466667   
...                   ...        ...       ...              ...   
2201509                 0       92.0       373       653.000000   
2201510                 0      353.0      2262      3447.700000   
2201511                 0       78.0       167       206.000000   
2201512                 0      105.0       461       500.633333   
2201513                 1       24.0       324       350.500000   

         Tot_Day_Suply  Tot_Drug_Cst  Fraud  
0                 8621      20606.08      0  
1                60953      79803.65      0  
2                  554        327.34      0  
3                10242      19778.34      0  
4                 1929       7416.39      0  
...                ...           ...    ...  
2201509          18237      12874.00      1  
2201510          88774     125113.79      1  
2201511           4626      14205.65      1  
2201512          12360      20087.75      1  
2201513          10202       9769.77      1  

[2201514 rows x 7 columns]

In [19]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.6346515921990085

Confusion Matrix:
 [[168383  51892]
 [108972 111056]]

Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.76      0.68    220275
           1       0.68      0.50      0.58    220028

    accuracy                           0.63    440303
   macro avg       0.64      0.63      0.63    440303
weighted avg       0.64      0.63      0.63    440303



In [20]:
df = pd.read_csv("../../labelled_data/part_D/features/partd_smote_features.csv")

In [22]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI","Unnamed: 0.1"],axis=1)

In [23]:
df

Prscrbr_Type_src   Tot_Benes  Tot_Clms  Tot_30day_Fills  \
0                       0  106.000000       324       369.800000   
1                       0  228.000000      1992      2145.666667   
2                       0   43.000000        57        57.700000   
3                       0   67.000000       218       404.933333   
4                       0   26.000000        48        76.466667   
...                   ...         ...       ...              ...   
2161908                 0   24.078133        49        52.392148   
2161909                 0  113.776623      1479      2939.901472   
2161910                 0  404.280422      7940     11588.867112   
2161911                 0  251.957151      4509      8041.917669   
2161912                 0  280.772723      1723      2932.311183   

         Tot_Day_Suply   Tot_Drug_Cst  Fraud  
0                 8621   20606.080000      0  
1                60953   79803.650000      0  
2                  554     327.340000      0  
3                10242   19778.340000      0  
4                 1929    7416.390000      0  
...                ...            ...    ...  
2161908           1508    3112.681219      1  
2161909          85151  187640.665985      1  
2161910         314310  848560.522106      1  
2161911         233873  319868.546902      1  
2161912          85955  269675.419123      1  

[2161913 rows x 7 columns]

In [24]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.6492646565660537

Confusion Matrix:
 [[187822  26902]
 [124750  92909]]

Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.87      0.71    214724
           1       0.78      0.43      0.55    217659

    accuracy                           0.65    432383
   macro avg       0.69      0.65      0.63    432383
weighted avg       0.69      0.65      0.63    432383



In [25]:
df = pd.read_csv("../../labelled_data/part_D/features/partd_rus_type_features.csv")

In [26]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI","Unnamed: 0.1"],axis=1)

In [27]:
df

Prscrbr_Type_src  Tot_Benes  Tot_Clms  Tot_30day_Fills  Tot_Day_Suply  \
0                  0      170.0       535       676.100000          13627   
1                  0       88.0      1025      1046.700000          28957   
2                  0      348.0      1995      4385.333333         127810   
3                  0       23.0       127       178.333333           4645   
4                  0       17.0        32        83.533333           2454   
5                  0       32.0       145       352.900000          10319   
6                  0      192.0      2254      3581.833333         106609   
7                  0       14.0        41        43.033333           1121   
8                  0       11.0        41        43.100000           1207   
9                  0       59.0        75        77.000000            791   
10                 1       13.0       144       215.000000           6442   
11                 0       94.0       584       860.133333          24125   
12                 0       78.0       167       206.000000           4626   

    Tot_Drug_Cst  FraudType  
0       12162.93          0  
1       41958.56          1  
2       67039.00          2  
3       15085.27          3  
4        3327.60          4  
5        6788.08          5  
6      198297.18          6  
7        3551.61          7  
8        2133.29          8  
9         554.31          9  
10       5967.03         10  
11      43079.90         11  
12      14205.65         12

In [28]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=423)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.0

Confusion Matrix:
 [[0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           5       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       1.0
          10       0.00      0.00      0.00       0.0
          11       0.00      0.00      0.00       1.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score

In [29]:
df = pd.read_csv("../../labelled_data/part_D/features/partd_ros_type_features.csv")

In [30]:
df = df.drop(["Unnamed: 0","PRSCRBR_NPI","Unnamed: 0.1"],axis=1)

In [31]:
df

Prscrbr_Type_src  Tot_Benes  Tot_Clms  Tot_30day_Fills  \
0                        0      106.0       324       369.800000   
1                        0      228.0      1992      2145.666667   
2                        0       43.0        57        57.700000   
3                        0       67.0       218       404.933333   
4                        0       26.0        48        76.466667   
...                    ...        ...       ...              ...   
14309836                 0       78.0       167       206.000000   
14309837                 0       78.0       167       206.000000   
14309838                 0       78.0       167       206.000000   
14309839                 0       78.0       167       206.000000   
14309840                 0       78.0       167       206.000000   

          Tot_Day_Suply  Tot_Drug_Cst  FraudType  
0                  8621      20606.08          0  
1                 60953      79803.65          0  
2                   554        327.34          0  
3                 10242      19778.34          0  
4                  1929       7416.39          0  
...                 ...           ...        ...  
14309836           4626      14205.65         12  
14309837           4626      14205.65         12  
14309838           4626      14205.65         12  
14309839           4626      14205.65         12  
14309840           4626      14205.65         12  

[14309841 rows x 7 columns]

In [32]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=423)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-sc

Accuracy: 0.17579295932275996

Confusion Matrix:
 [[     0  19127  19822   3958  45778  27329      0      0      0      0
   16913  87646      0]
 [     0      0      0      0 219944      0      0      0      0      0
       0      0      0]
 [     0  22027  10923   3705  40303  25614      0      0      0      0
   11117 106481      0]
 [     0      0      0      0  46451      0      0      0      0      0
   57612 115757      0]
 [     0      0      0      0 109855      0      0      0      0      0
       0 109975      0]
 [     0      0      0      0      0 220662      0      0      0      0
       0      0      0]
 [     0  23341  11540      0  11507  46679      0      0      0      0
       0 127111      0]
 [     0      0      0      0      0      0      0      0      0      0
       0 220177      0]
 [     0   6722      0   6688  46622  33225      0      0      0      0
   20091 106749      0]
 [     0 109933      0      0      0 109802      0      0      0      0
       0      

/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
