In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [13]:
df = pd.read_csv("../../labelled_data/part_B/features/partb_features_data.csv")

In [14]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Rndrng_Prvdr_Type'] = label_encoder.fit_transform(df['Rndrng_Prvdr_Type'])

In [15]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Rndrng_Prvdr_Gndr'] = label_encoder.fit_transform(df['Rndrng_Prvdr_Gndr'])

In [16]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['FraudType'] = label_encoder.fit_transform(df['FraudType'])

In [17]:
df = df.drop(["Unnamed: 0","Rndrng_NPI"],axis=1)

In [18]:
df

Rndrng_Prvdr_Type  Rndrng_Prvdr_Gndr  Tot_Srvcs  Tot_Benes  \
0                       39                  1      764.0      291.0   
1                       65                  1     5930.0     2633.0   
2                        5                  1     2003.0      167.0   
3                       56                  0      571.0       56.0   
4                       27                  1      125.0       89.0   
...                    ...                ...        ...        ...   
1100721                 22                  1      171.0      155.0   
1100722                 39                  0     1093.0      333.0   
1100723                 13                  1      415.0       66.0   
1100724                 63                  1      851.0      456.0   
1100725                 39                  0      884.0      407.0   

         Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  \
0             402812.00            85319.63           69175.78   
1             915291.00           227372.53          176497.74   
2             182532.48           101757.15           76938.82   
3              23680.00             9011.99            7224.35   
4             152154.00            30631.10           23962.85   
...                 ...                 ...                ...   
1100721       329504.00            32266.94           25803.90   
1100722       182515.00            93505.14           68252.03   
1100723        20985.00            16171.02           11759.42   
1100724       304460.56           113283.09           85463.83   
1100725       340479.02            90924.61           74063.76   

         Tot_Mdcr_Stdzd_Amt  Fraud  FraudType  
0                  66401.61      0          0  
1                 167363.18      0          0  
2                  80179.52      0          0  
3                   7301.35      0          0  
4                  23463.98      0          0  
...                     ...    ...        ...  
1100721            22622.59      0          0  
1100722            62671.75      0          0  
1100723            11851.98      0          0  
1100724            77169.73      0          0  
1100725            73646.68      0          0  

[1100726 rows x 10 columns]

In [19]:
X = df.drop(['Fraud', 'FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.9998955238796071

Confusion Matrix:
 [[220123      3]
 [    20      0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    220126
           1       0.00      0.00      0.00        20

    accuracy                           1.00    220146
   macro avg       0.50      0.50      0.50    220146
weighted avg       1.00      1.00      1.00    220146



In [25]:
df = pd.read_csv("../../labelled_data/part_B/features/partb_rus_features.csv")

In [26]:
df = df.drop(["Unnamed: 0","Rndrng_NPI","Unnamed: 0.1"],axis=1)

In [27]:
df

Rndrng_Prvdr_Type  Rndrng_Prvdr_Gndr  Tot_Srvcs  Tot_Benes  \
0                   58                  1      179.0      133.0   
1                   40                  1     1938.0     1023.0   
2                   53                  1      604.0      193.0   
3                   36                  0      236.0       54.0   
4                   70                  0     2817.0       89.0   
..                 ...                ...        ...        ...   
201                 78                  1     4146.0      781.0   
202                 26                  1       94.0       45.0   
203                 70                  1     1237.0       11.0   
204                 18                  1      632.0      177.0   
205                 39                  1       57.0       24.0   

     Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  \
0           30229.0            13396.09            5503.01   
1          671028.0           183976.13          141210.32   
2         1133045.0           108549.88           86518.05   
3           74284.0            20153.42           16121.87   
4          173978.0            70552.14           56161.94   
..              ...                 ...                ...   
201        998238.0           333015.83          253335.52   
202         15750.0            11082.67            7841.14   
203         45641.0            33723.68           26885.67   
204        418272.0           135167.73          107625.89   
205          7294.4             2593.63             828.82   

     Tot_Mdcr_Stdzd_Amt  Fraud  
0               5263.85      0  
1             138865.00      0  
2              89429.57      0  
3              14639.61      0  
4              52806.91      0  
..                  ...    ...  
201           228881.87      1  
202             7549.29      1  
203            25002.94      1  
204            96228.16      1  
205              810.51      1  

[206 rows x 9 columns]

In [29]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.5714285714285714

Confusion Matrix:
 [[18  2]
 [16  6]]

Classification Report:
               precision    recall  f1-score   support

           0       0.53      0.90      0.67        20
           1       0.75      0.27      0.40        22

    accuracy                           0.57        42
   macro avg       0.64      0.59      0.53        42
weighted avg       0.64      0.57      0.53        42



/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [30]:
df = pd.read_csv("../../labelled_data/part_B/features/partb_ros_features.csv")

In [31]:
df = df.drop(["Unnamed: 0","Rndrng_NPI","Unnamed: 0.1"],axis=1)

In [32]:
df

Rndrng_Prvdr_Type  Rndrng_Prvdr_Gndr  Tot_Srvcs  Tot_Benes  \
0                       39                  1      764.0      291.0   
1                       65                  1     5930.0     2633.0   
2                        5                  1     2003.0      167.0   
3                       56                  0      571.0       56.0   
4                       27                  1      125.0       89.0   
...                    ...                ...        ...        ...   
2181095                 39                  0     5263.0      583.0   
2181096                 73                  0     1355.0      197.0   
2181097                 55                  0       45.0       17.0   
2181098                  5                  1      544.0      111.0   
2181099                 55                  1       34.0       24.0   

         Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  \
0             402812.00            85319.63           69175.78   
1             915291.00           227372.53          176497.74   
2             182532.48           101757.15           76938.82   
3              23680.00             9011.99            7224.35   
4             152154.00            30631.10           23962.85   
...                 ...                 ...                ...   
2181095       797304.00           591578.26          443915.59   
2181096       141699.11           114326.91           86767.98   
2181097        28875.00             1916.61            1180.93   
2181098       101853.08            44113.45           31179.59   
2181099         7821.27             2558.48            1926.74   

         Tot_Mdcr_Stdzd_Amt  Fraud  
0                  66401.61      0  
1                 167363.18      0  
2                  80179.52      0  
3                   7301.35      0  
4                  23463.98      0  
...                     ...    ...  
2181095           436072.86      1  
2181096            93482.18      1  
2181097             1213.85      1  
2181098            30797.07      1  
2181099             1947.82      1  

[2181100 rows x 9 columns]

In [33]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.6733872816468754

Confusion Matrix:
 [[162604  55717]
 [ 86758 131141]]

Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.74      0.70    218321
           1       0.70      0.60      0.65    217899

    accuracy                           0.67    436220
   macro avg       0.68      0.67      0.67    436220
weighted avg       0.68      0.67      0.67    436220



In [34]:
df = pd.read_csv("../../labelled_data/part_B/features/partb_smote_features.csv")

In [35]:
df = df.drop(["Unnamed: 0","Rndrng_NPI","Unnamed: 0.1"],axis=1)

In [36]:
df

Rndrng_Prvdr_Type  Rndrng_Prvdr_Gndr    Tot_Srvcs    Tot_Benes  \
0                       39                  1   764.000000   291.000000   
1                       65                  1  5930.000000  2633.000000   
2                        5                  1  2003.000000   167.000000   
3                       56                  0   571.000000    56.000000   
4                       27                  1   125.000000    89.000000   
...                    ...                ...          ...          ...   
2142144                 53                  0   619.810162   117.984270   
2142145                 25                  1   244.931581    80.942454   
2142146                 35                  1  1273.124734   108.762793   
2142147                 18                  1  4108.360309   157.904550   
2142148                 57                  0   136.932271    90.588753   

         Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  \
0         402812.000000        85319.630000       69175.780000   
1         915291.000000       227372.530000      176497.740000   
2         182532.480000       101757.150000       76938.820000   
3          23680.000000         9011.990000        7224.350000   
4         152154.000000        30631.100000       23962.850000   
...                 ...                 ...                ...   
2142144    61751.217391        49360.731950       37496.765168   
2142145   525289.642077        18164.832569       14176.507835   
2142146   166706.381486        96367.158779       73512.655005   
2142147   587022.018933       456556.784847      358018.286947   
2142148    24363.812960        10535.303774        5951.674813   

         Tot_Mdcr_Stdzd_Amt  Fraud  
0              66401.610000      0  
1             167363.180000      0  
2              80179.520000      0  
3               7301.350000      0  
4              23463.980000      0  
...                     ...    ...  
2142144        40400.328511      1  
2142145        14155.308921      1  
2142146        74457.695885      1  
2142147       311220.813829      1  
2142148         5511.121330      1  

[2142149 rows x 9 columns]

In [37]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.6769157155194547

Confusion Matrix:
 [[152670  59752]
 [ 78667 137341]]

Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.72      0.69    212422
           1       0.70      0.64      0.66    216008

    accuracy                           0.68    428430
   macro avg       0.68      0.68      0.68    428430
weighted avg       0.68      0.68      0.68    428430



In [38]:
df = pd.read_csv("../../labelled_data/part_B/features/partb_rus_type_features.csv")

In [39]:
df = df.drop(["Unnamed: 0","Rndrng_NPI","Unnamed: 0.1"],axis=1)

In [40]:
df

Rndrng_Prvdr_Type  Rndrng_Prvdr_Gndr  Tot_Srvcs  Tot_Benes  \
0                  58                  1      179.0      133.0   
1                  24                  0      937.0      181.0   
2                  26                  1      745.0       37.0   
3                  24                  1       24.0       18.0   
4                  64                  1     1911.0      191.0   
5                   9                  1     4913.0      187.0   
6                  39                  1       84.0       27.0   
7                  12                  1      205.0       95.0   
8                  22                  1      242.0      177.0   
9                  21                  0      734.0      667.0   
10                 51                  1     1395.0      102.0   
11                  9                  1    13277.0      725.0   
12                 73                  0     1355.0      197.0   

    Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  Tot_Mdcr_Stdzd_Amt  \
0         30229.00            13396.09            5503.01             5263.85   
1        102219.34            74794.37           57189.21            55213.57   
2         34978.00            23798.82           17696.67            16890.06   
3           448.00              156.54             150.88              152.89   
4        408961.71           131982.22           96566.20           100945.32   
5        701734.01           545818.28          428190.59           371882.56   
6         15185.00             9429.72            5761.06             5788.47   
7        645500.00            14871.18           11622.38            11851.11   
8        228918.00            26580.47           21789.30            21066.43   
9        127700.00            41871.52           31161.16            30651.67   
10       138360.00           100556.21           78978.49            71050.28   
11      1578045.71           402458.02          301002.59           316486.95   
12       141699.11           114326.91           86767.98            93482.18   

    FraudType  
0           0  
1           1  
2           2  
3           3  
4           4  
5           5  
6           6  
7           7  
8           8  
9           9  
10         10  
11         11  
12         12

In [43]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=423)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.0

Confusion Matrix:
 [[0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       0.0
           8       0.00      0.00      0.00       0.0
           9       0.00      0.00      0.00       1.0
          11       0.00      0.00      0.00       1.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score

In [45]:
df = pd.read_csv("../../labelled_data/part_B/features/partb_ros_type_features.csv")

In [46]:
df = df.drop(["Unnamed: 0","Rndrng_NPI","Unnamed: 0.1"],axis=1)

In [47]:
df

Rndrng_Prvdr_Type  Rndrng_Prvdr_Gndr  Tot_Srvcs  Tot_Benes  \
0                        39                  1      764.0      291.0   
1                        65                  1     5930.0     2633.0   
2                         5                  1     2003.0      167.0   
3                        56                  0      571.0       56.0   
4                        27                  1      125.0       89.0   
...                     ...                ...        ...        ...   
14177145                 73                  0     1355.0      197.0   
14177146                 73                  0     1355.0      197.0   
14177147                 73                  0     1355.0      197.0   
14177148                 73                  0     1355.0      197.0   
14177149                 73                  0     1355.0      197.0   

          Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  \
0              402812.00            85319.63           69175.78   
1              915291.00           227372.53          176497.74   
2              182532.48           101757.15           76938.82   
3               23680.00             9011.99            7224.35   
4              152154.00            30631.10           23962.85   
...                  ...                 ...                ...   
14177145       141699.11           114326.91           86767.98   
14177146       141699.11           114326.91           86767.98   
14177147       141699.11           114326.91           86767.98   
14177148       141699.11           114326.91           86767.98   
14177149       141699.11           114326.91           86767.98   

          Tot_Mdcr_Stdzd_Amt  FraudType  
0                   66401.61          0  
1                  167363.18          0  
2                   80179.52          0  
3                    7301.35          0  
4                   23463.98          0  
...                      ...        ...  
14177145            93482.18         12  
14177146            93482.18         12  
14177147            93482.18         12  
14177148            93482.18         12  
14177149            93482.18         12  

[14177150 rows x 9 columns]

In [48]:
X = df.drop(['FraudType'], axis=1)
y = df['FraudType']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=423)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-sc

Accuracy: 0.27157856127642016

Confusion Matrix:
 [[ 30061  17900  34907      0      3   5956      0      2  33730    115
   34815  51840   9242]
 [  8115  32214  24233      0      0  24101      0      0  24142      0
   40203  40443  24383]
 [ 39595      0  39862      0      0  39541      0      0      0      0
   59582  39604      0]
 [     0 217713      0      0      0      0      0      0      0      0
       0      0      0]
 [     0      0 108633      0      0      0      0      0      0      0
       0 109348      0]
 [     0  27198  27339      0      0  27519      0      0      0      0
   54380  54659  27170]
 [     0      0      0      0      0      0      0      0      0      0
  218570      0      0]
 [     0      0  33505      0      0  16724      0      0  33668      0
   50450  66408  16546]
 [     0      0      0      0      0      0      0      0 218003      0
       0      0      0]
 [     0      0 218134      0      0      0      0      0      0      0
       0      

/Users/sujaykumar/miniconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
