In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
df = pd.read_csv("../../labelled_data/Combined/imputed_combined.csv")

In [4]:
cols = ['Rndrng_Prvdr_Crdntls',
'Rndrng_Prvdr_Gndr', 
'Rndrng_Prvdr_Type',
'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 
'Tot_HCPCS_Cds', 
'Tot_Benes_x',
'Tot_Srvcs', 
'Tot_Sbmtd_Chrg', 
'Tot_Mdcr_Alowd_Amt',
'Tot_Mdcr_Pymt_Amt', 
'Tot_Mdcr_Stdzd_Amt', 
'Drug_Sprsn_Ind_x',
'Drug_Tot_HCPCS_Cds', 
'Drug_Tot_Benes', 
'Drug_Tot_Srvcs',
'Drug_Sbmtd_Chrg', 
'Drug_Mdcr_Alowd_Amt', 
'Drug_Mdcr_Pymt_Amt',
       'Drug_Mdcr_Stdzd_Amt', 'Med_Sprsn_Ind', 'Med_Tot_HCPCS_Cds',
       'Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
       'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',
       'Bene_Avg_Age_x', 'Bene_Age_LT_65_Cnt_x', 'Bene_Age_65_74_Cnt_x',
       'Bene_Age_75_84_Cnt_x', 'Bene_Age_GT_84_Cnt_x', 'Bene_Feml_Cnt_x',
       'Bene_Male_Cnt_x', 'Bene_Race_Wht_Cnt_x', 'Bene_Race_Black_Cnt_x',
       'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt_x',
       'Bene_Race_NatInd_Cnt', 'Bene_Race_Othr_Cnt_x', 'Bene_Dual_Cnt_x',
       'Bene_Ndual_Cnt_x', 'Bene_CC_AF_Pct_x', 'Bene_CC_Alzhmr_Pct_x',
       'Bene_CC_Asthma_Pct_x', 'Bene_CC_Cncr_Pct_x', 'Bene_CC_CHF_Pct_x',
       'Bene_CC_CKD_Pct_x', 'Bene_CC_COPD_Pct_x', 'Bene_CC_Dprssn_Pct_x',
       'Bene_CC_Dbts_Pct_x', 'Bene_CC_Hyplpdma_Pct_x',
       'Bene_CC_Hyprtnsn_Pct_x', 'Bene_CC_IHD_Pct_x', 'Bene_CC_Opo_Pct_x',
       'Bene_CC_RAOA_Pct_x', 'Bene_CC_Sz_Pct_x', 'Bene_CC_Strok_Pct_x',
       'Bene_Avg_Risk_Scre_x', 'Rndrng_NPI', 'Fraud_x', 'FraudType_x',
'Prscrbr_Crdntls',
       'Prscrbr_Type_src', 'Tot_Clms', 'Tot_30day_Fills',
       'Tot_Drug_Cst', 'Tot_Day_Suply', 'GE65_Sprsn_Flag',
       'GE65_Tot_Clms', 'GE65_Tot_30day_Fills', 'GE65_Tot_Drug_Cst',
       'GE65_Tot_Day_Suply', 'GE65_Bene_Sprsn_Flag', 'GE65_Tot_Benes',
       'Brnd_Sprsn_Flag', 'Brnd_Tot_Clms', 'Brnd_Tot_Drug_Cst',
       'Gnrc_Sprsn_Flag', 'Gnrc_Tot_Clms', 'Gnrc_Tot_Drug_Cst',
       'Othr_Sprsn_Flag', 'Othr_Tot_Clms', 'Othr_Tot_Drug_Cst',
       'MAPD_Sprsn_Flag', 'MAPD_Tot_Clms', 'MAPD_Tot_Drug_Cst',
       'PDP_Sprsn_Flag', 'PDP_Tot_Clms', 'PDP_Tot_Drug_Cst',
       'LIS_Sprsn_Flag', 'LIS_Tot_Clms', 'LIS_Drug_Cst',
       'NonLIS_Sprsn_Flag', 'NonLIS_Tot_Clms', 'NonLIS_Drug_Cst',
       'Opioid_Tot_Clms', 'Opioid_Tot_Drug_Cst', 'Opioid_Tot_Suply',
       'Opioid_Tot_Benes', 'Opioid_Prscrbr_Rate', 'Opioid_LA_Tot_Clms',
       'Opioid_LA_Tot_Drug_Cst', 'Opioid_LA_Tot_Suply',
       'Opioid_LA_Tot_Benes', 'Opioid_LA_Prscrbr_Rate', 'Antbtc_Tot_Clms',
       'Antbtc_Tot_Drug_Cst', 'Antbtc_Tot_Benes',
       'Antpsyct_GE65_Sprsn_Flag', 'Antpsyct_GE65_Tot_Clms',
       'Antpsyct_GE65_Tot_Drug_Cst', 'Antpsyct_GE65_Tot_Benes',
       'Bene_Race_Api_Cnt_x', 
       'Bene_Race_Natind_Cnt_x', 
       'Rfrg_Prvdr_Type_Flag', 'Tot_Suplrs', 'Tot_Suplr_HCPCS_Cds',
       'Tot_Suplr_Benes', 'Tot_Suplr_Clms', 'Tot_Suplr_Srvcs',
       'Suplr_Sbmtd_Chrgs', 'Suplr_Mdcr_Alowd_Amt', 'Suplr_Mdcr_Pymt_Amt',
       'Suplr_Mdcr_Stdzd_Pymt_Amt', 'DME_Sprsn_Ind', 'DME_Tot_Suplrs',
       'DME_Tot_Suplr_HCPCS_Cds', 'DME_Tot_Suplr_Benes',
       'DME_Tot_Suplr_Clms', 'DME_Tot_Suplr_Srvcs',
       'DME_Suplr_Sbmtd_Chrgs', 'DME_Suplr_Mdcr_Alowd_Amt',
       'DME_Suplr_Mdcr_Pymt_Amt', 'DME_Suplr_Mdcr_Stdzd_Pymt_Amt',
       'POS_Sprsn_Ind', 'POS_Tot_Suplrs', 'POS_Tot_Suplr_HCPCS_Cds',
       'POS_Tot_Suplr_Benes', 'POS_Tot_Suplr_Clms', 'POS_Tot_Suplr_Srvcs',
       'POS_Suplr_Sbmtd_Chrgs', 'POS_Suplr_Mdcr_Alowd_Amt',
       'POS_Suplr_Mdcr_Pymt_Amt', 'POS_Suplr_Mdcr_Stdzd_Pymt_Amt',
       'Drug_Tot_Suplrs', 'Drug_Tot_Suplr_HCPCS_Cds',
       'Drug_Tot_Suplr_Benes', 'Drug_Tot_Suplr_Clms',
       'Drug_Tot_Suplr_Srvcs', 'Drug_Suplr_Sbmtd_Chrgs',
       'Drug_Suplr_Mdcr_Alowd_Amt', 'Drug_Suplr_Mdcr_Pymt_Amt',
       'Drug_Suplr_Mdcr_Stdzd_Pymt_Amt', 'Bene_Avg_Age',
       'Fraud', 'FraudType']

In [5]:
df = df[cols]

In [6]:
df = df.drop(["Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [7]:
df

Rndrng_Prvdr_Crdntls  Rndrng_Prvdr_Gndr  Rndrng_Prvdr_Type  \
0                       7310                0.0                 39   
1                       9043                0.0                 24   
2                       4737                1.0                 39   
3                       7895                0.0                 91   
4                       9043                1.0                 24   
...                      ...                ...                ...   
334369                  9043                1.0                 39   
334370                  7310                0.0                 24   
334371                  3446                0.0                 39   
334372                  7310                1.0                 39   
334373                 17582                1.0                 39   

        Rndrng_Prvdr_Mdcr_Prtcptg_Ind  Tot_HCPCS_Cds  Tot_Benes_x  Tot_Srvcs  \
0                                   1           16.0        291.0      764.0   
1                                   1           34.0        251.0      660.0   
2                                   1           35.0        359.0     1400.0   
3                                   1           92.0        739.0     3916.0   
4                                   1           43.0        285.0      922.0   
...                               ...            ...          ...        ...   
334369                              1           37.0        365.0     2272.0   
334370                              1           50.0        138.0      769.0   
334371                              1           34.0       1215.0     6097.0   
334372                              1           40.0        333.0     1093.0   
334373                              1           15.0        407.0      884.0   

        Tot_Sbmtd_Chrg  Tot_Mdcr_Alowd_Amt  Tot_Mdcr_Pymt_Amt  ...  \
0            402812.00            85319.63           69175.78  ...   
1            149315.45            49859.16           34786.35  ...   
2            238600.00           149023.89          114975.60  ...   
3            777162.00           277266.94          210439.56  ...   
4            139700.00            71391.30           52741.85  ...   
...                ...                 ...                ...  ...   
334369       587582.00           203150.57          157754.65  ...   
334370       109972.88            53888.01           40893.46  ...   
334371       696266.98           513866.65          390895.36  ...   
334372       182515.00            93505.14           68252.03  ...   
334373       340479.02            90924.61           74063.76  ...   

        Drug_Tot_Suplr_Benes  Drug_Tot_Suplr_Clms  Drug_Tot_Suplr_Srvcs  \
0                        0.0                  0.0                   0.0   
1                       17.0                 51.0                2002.0   
2                        0.0                  0.0                   0.0   
3                        0.0                  0.0                   0.0   
4                       11.0                 18.0                  18.0   
...                      ...                  ...                   ...   
334369                  11.0                 12.0                  12.0   
334370                  11.0                 15.0                2387.0   
334371                  16.0                 61.0                  61.0   
334372                   0.0                  0.0                   0.0   
334373                   0.0                  0.0                   0.0   

        Drug_Suplr_Sbmtd_Chrgs  Drug_Suplr_Mdcr_Alowd_Amt  \
0                         0.00                       0.00   
1                      7051.88                    2010.45   
2                         0.00                       0.00   
3                         0.00                       0.00   
4                       714.00                     594.00   
...                        ...                        ...   
334369                  462.00       

In [8]:
X = df.drop(['Fraud', 'FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.9998654205607477

Confusion Matrix:
 [[66866     2]
 [    7     0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     66868
           1       0.00      0.00      0.00         7

    accuracy                           1.00     66875
   macro avg       0.50      0.50      0.50     66875
weighted avg       1.00      1.00      1.00     66875



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
df = pd.read_csv("../../labelled_data/combined/combined_rus_features.csv")

In [16]:
df = df.drop(["Unnamed: 0","Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [17]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.5217391304347826

Confusion Matrix:
 [[6 9]
 [2 6]]

Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.40      0.52        15
           1       0.40      0.75      0.52         8

    accuracy                           0.52        23
   macro avg       0.57      0.57      0.52        23
weighted avg       0.63      0.52      0.52        23



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
df = pd.read_csv("../../labelled_data/combined/combined_ros_features.csv")

In [10]:
df = df.drop(["Unnamed: 0","Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [11]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.7243883106006221

Confusion Matrix:
 [[52491 14301]
 [22556 44380]]

Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.79      0.74     66792
           1       0.76      0.66      0.71     66936

    accuracy                           0.72    133728
   macro avg       0.73      0.72      0.72    133728
weighted avg       0.73      0.72      0.72    133728



In [12]:
df = pd.read_csv("../../labelled_data/combined/combined_smote_features.csv")

In [13]:
df = df.drop(["Unnamed: 0","Fraud_x","FraudType_x","Rndrng_NPI",],axis=1)

In [14]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.7311512415349887

Confusion Matrix:
 [[53004 12981]
 [22749 44166]]

Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.80      0.75     65985
           1       0.77      0.66      0.71     66915

    accuracy                           0.73    132900
   macro avg       0.74      0.73      0.73    132900
weighted avg       0.74      0.73      0.73    132900

