In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("../../labelled_data/DMEPOS/imputed_dmepos.csv")

In [3]:
df = df.drop(["Unnamed: 0","Rfrg_NPI"],axis=1)

In [4]:
df

Rfrg_Prvdr_Crdntls  Rfrg_Prvdr_Gndr  Rfrg_Prvdr_Type  \
0                     2362              0.0               44   
1                     3017              0.0               26   
2                     1629              1.0               44   
3                     2684              0.0              117   
4                     4511              1.0               87   
...                    ...              ...              ...   
383452                3017              1.0               44   
383453                2362              0.0               26   
383454                1186              0.0               44   
383455                2362              1.0               44   
383456                5465              1.0               44   

        Rfrg_Prvdr_Type_Flag  Tot_Suplrs  Tot_Suplr_HCPCS_Cds  \
0                        1.0           8                    7   
1                        1.0          28                   47   
2                        1.0          11                   44   
3                        1.0           5                   12   
4                        1.0           1                    1   
...                      ...         ...                  ...   
383452                   1.0          35                   67   
383453                   1.0          12                   17   
383454                   1.0          47                   56   
383455                   1.0          11                   27   
383456                   1.0           6                    8   

        Tot_Suplr_Benes  Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  \
0                  11.0             132              159           29869.97   
1                  33.0              97             1136           44435.62   
2                  19.0              65             1117           18711.69   
3                  23.0              29             4778           26951.30   
4                  13.0              13               13            2080.00   
...                 ...             ...              ...                ...   
383452             46.0             180             4981          107216.47   
383453             11.0              35              384           11429.84   
383454             86.0             502            11743          173452.58   
383455             14.0              55              322           19471.42   
383456             13.0              38               55            6707.76   

        ...  Bene_CC_Hyplpdma_Pct  Bene_CC_Hyprtnsn_Pct  Bene_CC_IHD_Pct  \
0       ...                  0.75                  0.75             0.32   
1       ...                  0.73                  0.75             0.39   
2       ...                  0.74                  0.75             0.53   
3       ...                  0.54                  0.69             0.48   
4       ...                  0.75                  0.75             0.00   
...     ...                   ...                   ...              ...   
383452  ...                  0.75                  0.75             0.50   
383453  ...                  0.75                  0.75             0.00   
383454  ...                  0.60                  0.73             0.66   
383455  ...                  0.75                  0.75             0.35   
383456  ...                  0.75                  0.75             0.00   

        Bene_CC_Opo_Pct  Bene_CC_RAOA_Pct  Bene_CC_Sz_Pct  Bene_CC_Strok_Pct  \
0                  0.00              0.64             0.0               0.00   
1                  0.00              0.58             0.0               0.00   
2                  0.00              0.68             0.0               0.00   
3                  0.00              0.75             0.0               0.00   
4                  0.00              0.75             0.0               0.00   
...                 ...               ...             ...                ...   
383452             0.40             

In [5]:
X = df.drop(['Fraud', 'FraudType'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.9997131382673551

Confusion Matrix:
 [[76670     0]
 [   22     0]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     76670
           1       0.00      0.00      0.00        22

    accuracy                           1.00     76692
   macro avg       0.50      0.50      0.50     76692
weighted avg       1.00      1.00      1.00     76692



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/metrics/_classification.py:

In [6]:
df = pd.read_csv("../../labelled_data/DMEPOS/dmepos_rus_features.csv")

In [7]:
df = df.drop(["Unnamed: 0.1","Unnamed: 0","Rfrg_NPI"],axis=1)

In [8]:
df

Rfrg_Prvdr_Crdntls  Rfrg_Prvdr_Gndr  Rfrg_Prvdr_Type  \
0                  4437              1.0               65   
1                  1997              1.0               65   
2                  4587              0.0               87   
3                   419              1.0               65   
4                  2362              0.0               30   
..                  ...              ...              ...   
199                3017              0.0               26   
200                2362              0.0               29   
201                3017              0.0               26   
202                3017              0.0               29   
203                3017              0.0               44   

     Rfrg_Prvdr_Type_Flag  Tot_Suplrs  Tot_Suplr_HCPCS_Cds  Tot_Suplr_Benes  \
0                     1.0           2                   10             16.0   
1                     1.0           6                   22             42.0   
2                     1.0           5                    9             18.0   
3                     1.0           5                    7             25.0   
4                     1.0          12                   18            112.0   
..                    ...         ...                  ...              ...   
199                   1.0          19                   22             20.0   
200                   1.0           4                   16             13.0   
201                   1.0           1                    1             17.0   
202                   0.0          14                   18             61.0   
203                   1.0           2                    3             20.0   

     Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  ...  \
0                18               41            4202.72  ...   
1               220              324           53997.47  ...   
2                34              172            6297.83  ...   
3                32             1503            8361.72  ...   
4               372            96088          437064.15  ...   
..              ...              ...                ...  ...   
199              58             2584           21190.91  ...   
200              44              468            5537.80  ...   
201              12               12             929.52  ...   
202              84              491           44971.91  ...   
203              15               26            1651.46  ...   

     Bene_CC_Dbts_Pct  Bene_CC_Hyplpdma_Pct  Bene_CC_Hyprtnsn_Pct  \
0                0.75                  0.75                  0.75   
1                0.60                  0.75                  0.75   
2                0.70                  0.61                  0.73   
3                0.56                  0.69                  0.59   
4                0.70                  0.63                  0.75   
..                ...                   ...                   ...   
199              0.75                  0.70                  0.75   
200              0.42                  0.65                  0.75   
201              0.75                  0.69                  0.75   
202              0.46                  0.57                  0.75   
203              0.55                  0.69                  0.75   

     Bene_CC_IHD_Pct  Bene_CC_Opo_Pct  Bene_CC_RAOA_Pct  Bene_CC_Sz_Pct  \
0               0.75             0.00              0.72             0.0   
1               0.67             0.20              0.69             0.0   
2               0.64             0.00              0.64             0.0   
3               0.63             0.00              0.50             0.0   
4               0.61             0.21              0.23             0.0   
..               ...              ...               ...             ...   
199             0.55             0.00              0.56             0.0   
200             0.21             0.00              0.40             0.0   
201             0.53             0.00             

In [10]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.43902439024390244

Confusion Matrix:
 [[ 7 15]
 [ 8 11]]

Classification Report:
               precision    recall  f1-score   support

           0       0.47      0.32      0.38        22
           1       0.42      0.58      0.49        19

    accuracy                           0.44        41
   macro avg       0.44      0.45      0.43        41
weighted avg       0.45      0.44      0.43        41



/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
df = pd.read_csv("../../labelled_data/DMEPOS/dmepos_ros_features.csv")

In [12]:
df = df.drop(["Unnamed: 0.1","Unnamed: 0","Rfrg_NPI"],axis=1)

In [13]:
df

Rfrg_Prvdr_Crdntls  Rfrg_Prvdr_Gndr  Rfrg_Prvdr_Type  \
0                     2362              0.0               44   
1                     3017              0.0               26   
2                     1629              1.0               44   
3                     2684              0.0              117   
4                     4511              1.0               87   
...                    ...              ...              ...   
766705                3017              0.0               26   
766706                3017              0.0               44   
766707                1186              1.0               26   
766708                3017              0.0               85   
766709                4277              1.0               65   

        Rfrg_Prvdr_Type_Flag  Tot_Suplrs  Tot_Suplr_HCPCS_Cds  \
0                        1.0           8                    7   
1                        1.0          28                   47   
2                        1.0          11                   44   
3                        1.0           5                   12   
4                        1.0           1                    1   
...                      ...         ...                  ...   
766705                   1.0           4                   11   
766706                   1.0           1                    5   
766707                   1.0           9                   27   
766708                   1.0           9                   18   
766709                   1.0           7                    7   

        Tot_Suplr_Benes  Tot_Suplr_Clms  Tot_Suplr_Srvcs  Suplr_Sbmtd_Chrgs  \
0                  11.0             132              159           29869.97   
1                  33.0              97             1136           44435.62   
2                  19.0              65             1117           18711.69   
3                  23.0              29             4778           26951.30   
4                  13.0              13               13            2080.00   
...                 ...             ...              ...                ...   
766705             20.0              20             1499           10756.06   
766706             11.0              35               58            8610.00   
766707             11.0              38              527           24189.32   
766708             20.0             197              256           24346.83   
766709             32.0              57            10044           49465.56   

        ...  Bene_CC_Dbts_Pct  Bene_CC_Hyplpdma_Pct  Bene_CC_Hyprtnsn_Pct  \
0       ...              0.75                  0.75                  0.75   
1       ...              0.75                  0.73                  0.75   
2       ...              0.68                  0.74                  0.75   
3       ...              0.64                  0.54                  0.69   
4       ...              0.00                  0.75                  0.75   
...     ...               ...                   ...                   ...   
766705  ...              0.44                  0.63                  0.75   
766706  ...              0.58                  0.75                  0.75   
766707  ...              0.41                  0.50                  0.75   
766708  ...              0.64                  0.65                  0.75   
766709  ...              0.35                  0.48                  0.75   

        Bene_CC_IHD_Pct  Bene_CC_Opo_Pct  Bene_CC_RAOA_Pct  Bene_CC_Sz_Pct  \
0                  0.32              0.0              0.64             0.0   
1                  0.39              0.0              0.58             0.0   
2                  0.53              0.0              0.68             0.0   
3                  0.48              0.0              0.75             0.0   
4                  0.00              0.0              0.75             0.0   
...                 ...              ...               ...             ...   
766705             0.54              0

In [14]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.5888797589701452

Confusion Matrix:
 [[53603 22929]
 [40113 36697]]

Classification Report:
               precision    recall  f1-score   support

           0       0.57      0.70      0.63     76532
           1       0.62      0.48      0.54     76810

    accuracy                           0.59    153342
   macro avg       0.59      0.59      0.58    153342
weighted avg       0.59      0.59      0.58    153342



In [15]:
df = pd.read_csv("../../labelled_data/DMEPOS/dmepos_smote_features.csv")

In [16]:
df = df.drop(["Unnamed: 0.1","Unnamed: 0","Rfrg_NPI"],axis=1)

In [17]:
X = df.drop(['Fraud'], axis=1)
y = df['Fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

/Users/sujaykumar/miniconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.6062702760913753

Confusion Matrix:
 [[46058 26924]
 [31574 44018]]

Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.63      0.61     72982
           1       0.62      0.58      0.60     75592

    accuracy                           0.61    148574
   macro avg       0.61      0.61      0.61    148574
weighted avg       0.61      0.61      0.61    148574

